In [1]:
import pandas as pd
from datetime import datetime

In [2]:
cds_rating = pd.read_csv("A:/NIIT/Project - Amazon Reviews/CDs_and_Vinyl.csv", header = None)
cds_rating.head()

            0               1    2           3
0  0001393774  A171I27YBM4FL6  5.0  1461888000
1  0001393774  A1H1DL4K669VQ9  5.0  1461888000
2  0001393774  A23WIHT5886G36  5.0  1461024000
3  0001393774  A3SZNOJP8OL26X  5.0  1459296000
4  0001393774  A3V5XBBT7OZG5G  5.0  1456185600

In [3]:
cds_rating.rename(columns = {0:"asin", 1:"reviewerID", 2:"rating", 3:"date"}, inplace = True)
cds_rating.head()

         asin      reviewerID  rating        date
0  0001393774  A171I27YBM4FL6     5.0  1461888000
1  0001393774  A1H1DL4K669VQ9     5.0  1461888000
2  0001393774  A23WIHT5886G36     5.0  1461024000
3  0001393774  A3SZNOJP8OL26X     5.0  1459296000
4  0001393774  A3V5XBBT7OZG5G     5.0  1456185600

In [4]:
date = []
for i in cds_rating['date']:
    i = datetime.utcfromtimestamp(i).strftime('%Y-%m-%d')
    date.append(i)
date

['2016-04-29',
 '2016-04-29',
 '2016-04-19',
 '2016-03-30',
 '2016-02-23',
 '2016-02-11',
 '2015-11-28',
 '2015-07-18',
 '2015-07-11',
 '2015-05-26',
 '2015-05-12',
 '2015-04-16',
 '2015-04-09',
 '2015-03-13',
 '2015-03-05',
 '2014-12-16',
 '2014-11-04',
 '2014-10-29',
 '2014-10-20',
 '2014-10-15',
 '2014-08-15',
 '2014-08-02',
 '2014-04-07',
 '2014-04-02',
 '2014-02-15',
 '2014-01-21',
 '2013-08-31',
 '2013-08-11',
 '2013-07-21',
 '2013-07-02',
 '2013-05-02',
 '2013-05-01',
 '2012-01-09',
 '2010-08-05',
 '2009-03-31',
 '2008-10-18',
 '2006-12-29',
 '2005-11-01',
 '1998-11-22',
 '1998-09-23',
 '2018-02-22',
 '2018-02-21',
 '2018-02-18',
 '2018-02-14',
 '2018-02-14',
 '2018-02-11',
 '2018-02-10',
 '2018-02-06',
 '2018-02-03',
 '2018-01-29',
 '2018-01-28',
 '2018-01-27',
 '2018-01-27',
 '2018-01-20',
 '2018-01-18',
 '2018-01-15',
 '2018-01-11',
 '2018-01-10',
 '2018-01-04',
 '2017-12-27',
 '2017-12-25',
 '2017-12-23',
 '2017-12-22',
 '2017-12-21',
 '2017-12-21',
 '2017-12-19',
 '2017-12-18',
 '2017-12-17',
 '2017-12-16',
 '2017-12-11',
 '2017-12-08',
 '2017-12-07',
 '2017-12-03',
 '2017-11-24',
 '2017-11-24',
 '2017-11-16',
 '2017-11-15',
 '2017-11-12',
 '2017-11-03',
 '2017-10-12',
 '2017-09-18',
 '2017-09-14',
 '2017-08-22',
 '2017-08-03',
 '2017-07-22',
 '2017-07-22',
 '2017-07-10',
 '2017-05-30',
 '2017-05-07',
 '2017-04-21',
 '2017-04-04',
 '2017-03-19',
 '2017-03-16',
 '2017-03-09',
 '2017-02-26',
 '2017-02-20',
 '2017-02-20',
 '2017-02-15',
 '2017-02-11',
 '2017-02-10',
 '2017-02-10',
 '2017-02-08',
 '2017-02-08',
 '2017-02-03',
 '2017-02-02',
 '2017-02-01',
 '2017-01-30',
 '2017-01-26',
 '2017-01-25',
 '2017-01-24',
 '2017-01-23',
 '2017-01-22',
 '2017-01-19',
 '2017-01-17',
 '2017-01-16',
 '2017-01-15',
 '2017-01-11',
 '2017-01-09',
 '2017-01-08',
 '2017-01-06',
 '2017-01-06',
 '2017-01-06',
 '2017-01-03',
 '2017-01-02',
 '2017-01-02',
 '2017-01-02',
 '2017-01-01',
 '2016-12-31',
 '2016-12-30',
 '2016-12-26',
 '2016-12-25',
 '2016-12-25',
 '2016-12-25',
 '2016-12-24',
 '2016-12-23',
 '2016-12-22',
 '2016-12-21',
 '2016-12-20',
 '2016-12-15',
 '2016-12-13',
 '2016-12-11',
 '2016-12-11',
 '2016-12-10',
 '2016-12-10',
 '2016-12-09',
 '2016-12-09',
 '2016-12-09',
 '2016-12-06',
 '2016-12-05',
 '2016-12-05',
 '2016-12-03',
 '2016-12-02',
 '2016-12-01',
 '2016-11-30',
 '2016-11-15',
 '2016-10-29',
 '2016-10-24',
 '2016-10-09',
 '2016-10-01',
 '2016-08-15',
 '2016-08-15',
 '2016-08-11',
 '2016-07-19',
 '2016-06-23',
 '2016-06-04',
 '2016-05-29',
 '2016-05-08',
 '2016-05-07',
 '2016-04-24',
 '2016-04-23',
 '2016-04-03',
 '2016-03-24',
 '2016-03-15',
 '2016-03-14',
 '2016-03-06',
 '2016-03-04',
 '2016-02-28',
 '2016-02-19',
 '2016-02-08',
 '2016-02-06',
 '2016-02-03',
 '2016-02-02',
 '2016-02-02',
 '2016-02-01',
 '2016-02-01',
 '2016-01-29',
 '2016-01-27',
 '2016-01-27',
 '2016-01-25',
 '2016-01-22',
 '2016-01-22',
 '2016-01-21',
 '2016-01-21',
 '2016-01-19',
 '2016-01-19',
 '2016-01-18',
 '2016-01-18',
 '2016-01-15',
 '2016-01-08',
 '2016-01-07',
 '2015-12-27',
 '2015-12-16',
 '2015-12-13',
 '2015-12-08',
 '2015-12-06',
 '2015-12-05',
 '2015-12-02',
 '2015-11-29',
 '2015-11-23',
 '2015-11-21',
 '2015-11-16',
 '2015-11-12',
 '2015-10-19',
 '2015-10-17',
 '2015-10-09',
 '2015-10-07',
 '2015-08-31',
 '2015-08-15',
 '2015-08-05',
 '2015-08-05',
 '2015-08-05',
 '2015-07-29',
 '2015-07-18',
 '2015-07-14',
 '2015-07-08',
 '2015-07-01',
 '2015-06-15',
 '2015-06-10',
 '2015-06-01',
 '2015-05-23',
 '2015-05-16',
 '2015-05-15',
 '2015-05-02',
 '2015-04-20',
 '2015-04-09',
 '2015-04-01',
 '2015-03-28',
 '2015-03-08',
 '2015-03-08',
 '2015-03-05',
 '2015-03-05',
 '2015-03-05',
 '2015-03-01',
 '2015-02-28',
 '2015-02-23',
 '2015-02-22',
 '2015-02-19',
 '2015-02-18',
 '2015-02-17',
 '2015-02-17',
 '2015-02-16',
 '2015-02-13',
 '2015-02-06',
 '2015-02-04',
 '2015-02-04',
 '2015-02-04',
 '2015-02-04',
 '2015-02-01',
 '2015-01-31',
 '2015-01-27',
 '2015-01-20',
 '2015-01-19',
 '2015-01-16',
 '2015-01-16',
 '2015-01-15',
 '2015-01-15',
 '2015-01-13',
 '2015-01-13',
 '2015-01-12',
 '2015-01-12',
 '2015-01-09',
 '2015-01-08',
 '2015-01-08',
 '2015-01-07',
 '2015-01-05',
 '2015-01-04',
 '2015-01-04',
 '2015-01-04',
 '2015-01-03',
 '2015-01-03',
 '2015-01-03',
 '2015-01-01',
 '2015-01-01',
 '2015-01-01',
 '2015-01-01',
 '2014-12-29',
 '2014-12-26',
 '2014-12-26',
 '2014-12-26',
 '2014-12-24',
 '2014-12-23',
 '2014-12-22',
 '2014-12-21',
 '2014-12-20',
 '2014-12-19',
 '2014-12-19',
 '2014-12-18',
 '2014-12-18',
 '2014-12-18',
 '2014-12-18',
 '2014-12-18',
 '2014-12-14',
 '2014-12-13',
 '2014-12-12',
 '2014-12-11',
 '2014-12-10',
 '2014-12-09',
 '2014-12-09',
 '2014-12-09',
 '2014-12-09',
 '2014-12-08',
 '2014-12-08',
 '2014-12-07',
 '2014-12-07',
 '2014-12-06',
 '2014-12-04',
 '2014-12-02',
 '2014-12-01',
 '2014-11-27',
 '2014-11-24',
 '2014-11-19',
 '2014-11-19',
 '2014-11-14',
 '2014-11-01',
 '2014-10-27',
 '2014-10-25',
 '2014-10-22',
 '2014-10-19',
 '2014-10-01',
 '2014-09-26',
 '2014-09-03',
 '2014-08-15',
 '2014-08-15',
 '2014-08-08',
 '2014-07-27',
 '2014-07-23',
 '2014-07-18',
 '2014-07-02',
 '2014-06-30',
 '2014-05-29',
 '2014-04-18',
 '2014-04-02',
 '2014-03-30',
 '2014-03-06',
 '2014-03-04',
 '2014-03-03',
 '2014-02-26',
 '2014-02-26',
 '2014-02-18',
 '2014-02-15',
 '2014-02-11',
 '2014-02-10',
 '2014-02-08',
 '2014-02-07',
 '2014-02-04',
 '2014-02-01',
 '2014-01-30',
 '2014-01-28',
 '2014-01-28',
 '2014-01-26',
 '2014-01-18',
 '2014-01-16',
 '2014-01-13',
 '2014-01-13',
 '2014-01-08',
 '2014-01-07',
 '2014-01-06',
 '2014-01-06',
 '2014-01-03',
 '2014-01-02',
 '2014-01-02',
 '2014-01-02',
 '2014-01-01',
 '2013-12-29',
 '2013-12-29',
 '2013-12-27',
 '2013-12-25',
 '2013-12-25',
 '2013-12-21',
 '2013-12-18',
 '2013-12-18',
 '2013-12-17',
 '2013-12-16',
 '2013-12-14',
 '2013-12-12',
 '2013-12-09',
 '2013-12-05',
 '2013-12-03',
 '2013-12-01',
 '2013-11-29',
 '2013-11-28',
 '2013-11-20',
 '2013-11-15',
 '2013-11-10',
 '2013-11-05',
 '2013-10-13',
 '2013-10-06',
 '2013-08-29',
 '2013-08-28',
 '2013-08-15',
 '2013-08-09',
 '2013-07-06',
 '2013-05-26',
 '2013-05-17',
 '2013-05-15',
 '2013-05-09',
 '2013-05-09',
 '2013-03-18',
 '2013-03-17',
 '2013-03-16',
 '2013-03-14',
 '2013-03-09',
 '2013-03-03',
 '2013-02-26',
 '2013-02-25',
 '2013-02-23',
 '2013-02-22',
 '2013-02-17',
 '2013-02-13',
 '2013-02-11',
 '2013-02-04',
 '2013-02-04',
 '2013-01-20',
 '2013-01-18',
 '2013-01-17',
 '2013-01-17',
 '2013-01-15',
 '2013-01-15',
 '2013-01-14',
 '2013-01-14',
 '2013-01-13',
 '2013-01-11',
 '2013-01-11',
 '2013-01-10',
 '2013-01-09',
 '2013-01-08',
 '2013-01-08',
 '2013-01-06',
 '2013-01-02',
 '2013-01-01',
 '2013-01-01',
 '2013-01-01',
 '2012-12-31',
 '2012-12-31',
 '2012-12-30',
 '2012-12-28',
 '2012-12-28',
 '2012-12-28',
 '2012-12-26',
 '2012-12-25',
 '2012-12-25',
 '2012-12-25',
 '2012-12-24',
 '2012-12-24',
 '2012-12-22',
 '2012-12-21',
 '2012-12-20',
 '2012-12-20',
 '2012-12-20',
 '2012-12-19',
 '2012-12-19',
 '2012-12-19',
 '2012-12-19',
 '2012-12-18',
 '2012-12-15',
 '2012-12-13',
 '2012-12-11',
 '2012-12-10',
 '2012-12-10',
 '2012-12-08',
 '2012-12-07',
 '2012-12-05',
 '2012-12-05',
 '2012-12-02',
 '2012-11-30',
 '2012-11-26',
 '2012-11-26',
 '2012-11-22',
 '2012-09-25',
 '2012-06-22',
 '2012-06-11',
 '2012-05-07',
 '2012-03-20',
 '2012-02-11',
 '2012-01-18',
 '2012-01-12',
 '2012-01-10',
 '2011-12-30',
 '2011-12-29',
 '2011-12-26',
 '2011-12-05',
 '2011-11-21',
 '2011-09-07',
 '2011-01-20',
 '2011-01-04',
 '2010-12-27',
 '2010-12-12',
 '2010-11-27',
 '2010-11-01',
 '2010-11-01',
 '2010-06-24',
 '2010-04-23',
 '2010-02-13',
 '2010-02-12',
 '2010-02-11',
 '2010-01-26',
 '2010-01-21',
 '2010-01-09',
 '2009-12-28',
 '2009-12-28',
 '2009-12-08',
 '2009-12-07',
 '2009-12-05',
 '2009-06-13',
 '2009-04-22',
 '2009-04-04',
 '2009-01-30',
 '2009-01-14',
 '2009-01-12',
 '2009-01-11',
 '2009-01-08',
 '2009-01-07',
 '2008-12-23',
 '2008-11-02',
 '2008-07-25',
 '2008-07-12',
 '2008-05-18',
 '2008-05-13',
 '2008-04-21',
 '2008-04-08',
 '2008-03-18',
 '2008-03-18',
 '2008-01-19',
 '2008-01-18',
 '2008-01-07',
 '2008-01-07',
 '2008-01-06',
 '2007-12-28',
 '2007-12-25',
 '2007-12-04',
 '2007-12-03',
 '2007-11-30',
 '2007-11-17',
 '2007-11-09',
 '2007-08-20',
 '2007-06-29',
 '2007-05-08',
 '2007-03-08',
 '2007-03-08',
 '2007-01-29',
 '2007-01-22',
 '2007-01-19',
 '2007-01-18',
 '2007-01-18',
 '2007-01-16',
 '2007-01-15',
 '2007-01-11',
 '2007-01-11',
 '2007-01-11',
 '2007-01-04',
 '2007-01-03',
 '2006-12-30',
 '2006-12-28',
 '2006-12-22',
 '2006-12-12',
 '2006-11-27',
 '2006-11-14',
 '2006-11-11',
 '2006-06-25',
 '2006-02-22',
 '2006-02-02',
 '2006-01-15',
 '2006-01-01',
 '2005-12-29',
 '2005-12-21',
 '2005-12-17',
 '2005-12-11',
 '2005-12-09',
 '2005-12-08',
 '2005-12-06',
 '2005-11-25',
 '2005-11-22',
 '2005-11-21',
 '2005-11-13',
 '2005-11-11',
 '2005-11-10',
 '2005-11-04',
 '2005-10-08',
 '2005-01-09',
 '2005-01-04',
 '2005-01-01',
 '2004-12-26',
 '2004-12-25',
 '2004-12-12',
 '2004-12-08',
 '2004-12-08',
 '2004-12-06',
 '2004-12-05',
 '2004-11-19',
 '2004-11-16',
 '2004-11-13',
 '2004-08-30',
 '2004-08-28',
 '2004-08-22',
 '2004-01-23',
 '2004-01-03',
 '2003-12-28',
 '2003-12-22',
 '2003-12-16',
 '2003-12-16',
 '2003-12-15',
 '2003-12-12',
 '2003-12-10',
 '2003-12-07',
 '2003-12-07',
 '2003-12-05',
 '2003-12-04',
 '2003-12-03',
 '2003-12-02',
 '2003-12-01',
 '2003-11-30',
 '2003-11-29',
 '2003-11-23',
 '2003-10-01',
 '2003-05-30',
 '2003-05-23',
 '2003-01-18',
 '2003-01-01',
 '2002-12-31',
 '2002-12-22',
 '2002-12-21',
 '2002-12-21',
 '2002-12-20',
 '2002-12-19',
 '2002-12-17',
 '2002-12-16',
 '2002-12-11',
 '2002-12-11',
 '2002-12-07',
 '2002-11-30',
 '2002-11-30',
 '2002-11-20',
 '2002-11-03',
 '2002-09-05',
 '2002-07-23',
 '2002-03-13',
 '2002-02-14',
 '2002-01-25',
 '2001-12-19',
 '2001-12-03',
 '2001-11-23',
 '2001-11-18',
 '2001-11-08',
 '2001-11-06',
 '2001-10-25',
 '2001-10-09',
 '2001-08-31',
 '2001-08-23',
 '2001-08-11',
 '2000-12-30',
 '2000-12-21',
 '2000-12-15',
 '2000-11-28',
 '2000-11-27',
 '2000-11-19',
 '2000-08-05',
 '2000-06-08',
 '2000-04-08',
 '2000-04-04',
 '2000-02-21',
 '2000-01-01',
 '1999-12-26',
 '1999-12-23',
 '1999-12-22',
 '1999-12-20',
 '1999-12-14',
 '1999-12-03',
 '1999-12-01',
 '1999-11-30',
 '1999-11-28',
 '1999-11-27',
 '1999-11-13',
 '1999-09-28',
 '1999-02-04',
 '1999-01-07',
 '1998-12-21',
 '1998-12-10',
 '2007-01-09',
 '2005-02-21',
 '2004-01-10',
 '2014-05-13',
 '2014-04-11',
 '2013-10-14',
 '2013-06-04',
 '2002-11-01',
 '2002-05-20',
 '2002-01-22',
 '2001-12-30',
 '2000-10-04',
 '2015-03-18',
 '2014-10-23',
 '2014-08-01',
 '2013-12-20',
 '2010-05-30',
 '2007-08-10',
 '2007-02-09',
 '2006-06-12',
 '2005-08-02',
 '2003-07-03',
 '2002-07-08',
 '2002-05-15',
 '2002-01-08',
 '2001-08-24',
 '2001-07-16',
 '2001-02-14',
 '2000-10-19',
 '1999-12-31',
 '2012-05-07',
 '2010-12-30',
 '2009-07-27',
 '2008-06-18',
 '2007-08-21',
 '2007-03-20',
 '2001-04-24',
 '2000-04-20',
 '2015-01-29',
 '2015-01-16',
 '2014-12-11',
 '2014-11-29',
 '2014-11-16',
 '2014-11-09',
 '2014-08-02',
 '2014-07-26',
 '2014-04-29',
 '2014-03-27',
 '2014-02-13',
 '2014-02-08',
 '2014-01-16',
 '2014-01-01',
 '2013-06-24',
 '2013-05-02',
 '2013-04-30',
 '2013-04-19',
 '2013-01-13',
 '2012-05-09',
 '2004-02-10',
 '2003-07-28',
 '2002-12-31',
 '2002-12-29',
 '2000-12-03',
 '2000-12-03',
 '2014-02-27',
 '2013-09-11',
 '2012-10-12',
 '2012-09-29',
 '2010-06-19',
 '2009-11-08',
 '2006-07-31',
 '2005-09-17',
 '2005-08-03',
 '2004-07-04',
 '2005-12-19',
 '2005-09-08',
 '2004-01-03',
 '2015-01-13',
 '2014-12-31',
 '2014-12-04',
 '2014-08-03',
 '2014-01-19',
 '2013-11-30',
 '2013-08-11',
 '2013-04-29',
 '2013-02-12',
 '2013-02-07',
 '2012-12-12',
 '2012-12-10',
 '2012-12-03',
 '2012-11-11',
 '2011-09-26',
 '2011-07-03',
 '2011-03-31',
 '2011-03-31',
 '2011-02-12',
 '2011-01-03',
 '2010-05-28',
 '2010-03-09',
 '2009-03-26',
 '2009-01-21',
 '2007-12-26',
 '2007-10-10',
 '2007-08-08',
 '2007-01-03',
 '2006-03-08',
 '2005-12-21',
 '2006-05-14',
 '2005-11-02',
 '2005-10-16',
 '2016-10-18',
 '2016-08-29',
 '2016-08-15',
 '2016-08-04',
 '2016-07-24',
 '2016-07-09',
 '2016-06-21',
 '2016-06-16',
 '2016-02-13',
 '2016-01-15',
 '2015-11-18',
 '2015-10-31',
 '2015-10-24',
 '2015-10-24',
 '2015-10-10',
 '2015-10-09',
 '2015-09-05',
 '2015-08-29',
 '2015-08-03',
 '2015-07-29',
 '2015-07-11',
 '2015-07-08',
 '2015-06-25',
 '2015-06-18',
 '2015-06-07',
 '2015-06-04',
 '2015-05-24',
 '2015-04-07',
 '2015-03-03',
 '2015-03-02',
 '2015-03-01',
 '2015-02-20',
 '2015-02-10',
 '2015-01-31',
 '2015-01-26',
 '2015-01-25',
 '2015-01-21',
 '2015-01-18',
 '2015-01-01',
 '2014-12-15',
 '2014-12-02',
 '2014-11-30',
 '2014-11-19',
 '2014-11-12',
 '2014-11-04',
 '2014-10-30',
 '2014-10-15',
 '2014-10-03',
 '2014-10-02',
 '2014-09-13',
 '2014-09-08',
 '2014-08-26',
 '2014-08-25',
 '2014-08-08',
 '2014-07-21',
 '2014-07-09',
 '2014-07-07',
 '2014-07-06',
 '2014-07-03',
 '2014-07-03',
 '2014-06-29',
 '2014-06-29',
 '2014-06-02',
 '2014-05-22',
 '2014-05-12',
 '2014-04-25',
 '2014-03-22',
 '2014-03-17',
 '2014-03-17',
 '2014-03-17',
 '2014-03-07',
 '2014-03-06',
 '2014-03-01',
 '2014-02-26',
 '2014-02-08',
 '2014-01-16',
 '2014-01-06',
 '2013-12-04',
 '2013-11-10',
 '2013-10-23',
 '2013-10-21',
 '2013-10-18',
 '2013-09-26',
 '2013-09-14',
 '2013-09-13',
 '2013-09-01',
 '2013-08-02',
 '2013-07-25',
 '2013-07-24',
 '2013-06-08',
 '2013-05-10',
 '2013-05-03',
 '2013-02-02',
 '2013-01-30',
 '2013-01-30',
 '2013-01-27',
 '2013-01-16',
 '2012-12-23',
 '2012-12-15',
 '2012-11-08',
 '2012-10-28',
 '2012-10-17',
 '2012-10-02',
 '2012-09-30',
 '2012-07-13',
 '2012-06-12',
 '2012-02-25',
 '2011-12-06',
 '2011-09-05',
 '2011-08-04',
 '2011-04-20',
 '2011-03-24',
 '2011-03-19',
 '2011-02-11',
 '2010-11-11',
 '2010-09-12',
 '2010-09-05',
 '2010-07-01',
 '2010-01-26',
 '2009-12-21',
 '2009-11-02',
 '2009-10-03',
 '2009-04-11',
 '2009-04-04',
 '2009-02-08',
 '2009-01-12',
 '2008-12-21',
 '2008-02-27',
 '2007-12-14',
 '2006-08-08',
 '2006-04-13',
 '2006-02-22',
 '2015-01-16',
 '2014-11-11',
 '2014-09-22',
 '2014-09-10',
 '2014-06-07',
 '2014-05-05',
 '2013-12-04',
 '2013-09-11',
 '2013-08-16',
 '2013-08-13',
 '2013-08-08',
 '2013-08-05',
 '2013-07-05',
 '2013-06-02',
 '2013-04-14',
 '2013-03-27',
 '2013-02-15',
 '2013-02-06',
 '2013-01-26',
 '2013-01-16',
 '2012-12-26',
 '2012-12-06',
 '2012-11-06',
 '2012-10-17',
 '2012-08-16',
 '2012-07-31',
 '2012-05-24',
 '2012-04-18',
 '2012-03-26',
 '2012-03-15',
 '2012-01-13',
 '2011-12-05',
 '2011-11-28',
 '2010-09-30',
 '2009-12-11',
 '2009-03-11',
 '2009-02-15',
 '2009-01-28',
 '2009-01-26',
 '2009-01-15',
 '2008-10-12',
 '2008-05-15',
 '2008-04-21',
 '2008-03-03',
 '2008-02-21',
 '2008-01-10',
 '2007-10-12',
 '2007-10-05',
 '2007-09-28',
 '2007-07-28',
 '2007-06-28',
 '2007-06-14',
 '2007-06-12',
 '2007-05-28',
 '2007-04-01',
 '2007-03-04',
 '2007-02-18',
 '2007-02-13',
 '2007-02-12',
 '2007-02-11',
 '2007-02-07',
 '2007-01-21',
 '2007-01-12',
 '2007-01-10',
 '2006-10-11',
 '2006-07-25',
 '2006-05-12',
 '2006-05-05',
 '2006-04-24',
 '2006-04-15',
 '2003-04-11',
 ...]

In [5]:
cds_rating.date = date
cds_rating.head()

         asin      reviewerID  rating        date
0  0001393774  A171I27YBM4FL6     5.0  2016-04-29
1  0001393774  A1H1DL4K669VQ9     5.0  2016-04-29
2  0001393774  A23WIHT5886G36     5.0  2016-04-19
3  0001393774  A3SZNOJP8OL26X     5.0  2016-03-30
4  0001393774  A3V5XBBT7OZG5G     5.0  2016-02-23

In [6]:
cds_rating.isnull().sum()

asin          0
reviewerID    0
rating        0
date          0
dtype: int64

In [7]:
cds_rating.drop_duplicates(keep='first', inplace = True)
cds_rating

               asin      reviewerID  rating        date
0        0001393774  A171I27YBM4FL6     5.0  2016-04-29
1        0001393774  A1H1DL4K669VQ9     5.0  2016-04-29
2        0001393774  A23WIHT5886G36     5.0  2016-04-19
3        0001393774  A3SZNOJP8OL26X     5.0  2016-03-30
4        0001393774  A3V5XBBT7OZG5G     5.0  2016-02-23
...             ...             ...     ...         ...
4543364  B01HJG3VZI  A1KCWOF28NPM3M     5.0  2017-11-04
4543365  B01HJG3UQI   ASOJC2B605GDG     5.0  2017-04-24
4543366  B01HJG3UQI  A13EWHP1W5X77J     4.0  2016-12-06
4543367  B01HJG3UQI  A1QN6Z2E6M0S2D     5.0  2016-10-13
4543368  B01HJHLNIY   AF65C8QK9NNXP     5.0  2016-07-20

[4470329 rows x 4 columns]

In [8]:
off_rating = pd.read_csv("A:/NIIT/Project - Amazon Reviews/Office_Products.csv", header = None)
off_rating.head()

            0               1    2           3
0  0140503528  A2WJLOXXIB7NF3  3.0  1162512000
1  0140503528  A1RKICUK0GG6VF  5.0  1147132800
2  0140503528  A1QA5E50M398VW  5.0  1142035200
3  0140503528  A3N0HBW8IP8CZQ  5.0   980294400
4  0140503528  A1K1JW1C5CUSUZ  5.0   964915200

In [9]:
off_rating.rename(columns = {0:"asin", 1:"reviewerID", 2:"rating", 3:"date"}, inplace = True)
off_rating.head()

         asin      reviewerID  rating        date
0  0140503528  A2WJLOXXIB7NF3     3.0  1162512000
1  0140503528  A1RKICUK0GG6VF     5.0  1147132800
2  0140503528  A1QA5E50M398VW     5.0  1142035200
3  0140503528  A3N0HBW8IP8CZQ     5.0   980294400
4  0140503528  A1K1JW1C5CUSUZ     5.0   964915200

In [10]:
date = []
for i in off_rating['date']:
    i = datetime.utcfromtimestamp(i).strftime('%Y-%m-%d')
    date.append(i)
date

['2006-11-03',
 '2006-05-09',
 '2006-03-11',
 '2001-01-24',
 '2000-07-30',
 '2017-11-24',
 '2017-11-07',
 '2017-11-07',
 '2017-10-12',
 '2017-09-17',
 '2017-09-15',
 '2017-09-07',
 '2017-08-25',
 '2017-07-18',
 '2017-06-27',
 '2017-06-17',
 '2017-06-10',
 '2017-06-10',
 '2017-04-25',
 '2017-03-22',
 '2017-03-07',
 '2017-03-03',
 '2017-02-19',
 '2017-01-23',
 '2017-01-13',
 '2016-12-21',
 '2016-12-09',
 '2016-11-02',
 '2016-09-26',
 '2016-08-14',
 '2016-07-26',
 '2016-07-22',
 '2016-06-25',
 '2016-05-20',
 '2016-03-20',
 '2016-03-18',
 '2016-03-17',
 '2016-03-11',
 '2016-02-21',
 '2016-02-07',
 '2016-01-26',
 '2016-01-23',
 '2016-01-06',
 '2015-10-19',
 '2015-10-17',
 '2015-09-17',
 '2015-08-02',
 '2015-07-30',
 '2015-07-30',
 '2015-07-21',
 '2015-07-13',
 '2015-06-30',
 '2015-06-26',
 '2015-06-22',
 '2015-05-08',
 '2015-03-30',
 '2015-03-10',
 '2015-03-06',
 '2015-03-02',
 '2015-02-18',
 '2015-01-21',
 '2015-01-18',
 '2015-01-16',
 '2015-01-06',
 '2015-01-03',
 '2015-01-01',
 '2014-12-15',
 '2014-12-09',
 '2014-11-27',
 '2014-11-16',
 '2014-11-09',
 '2014-10-05',
 '2014-08-21',
 '2014-08-01',
 '2014-07-21',
 '2014-06-24',
 '2014-05-27',
 '2014-05-16',
 '2014-05-12',
 '2014-05-10',
 '2014-05-05',
 '2014-03-28',
 '2014-02-12',
 '2014-02-03',
 '2014-01-20',
 '2014-01-13',
 '2013-12-28',
 '2013-12-17',
 '2013-11-07',
 '2013-10-07',
 '2013-10-06',
 '2013-10-03',
 '2013-09-22',
 '2013-08-17',
 '2013-05-07',
 '2013-04-25',
 '2013-03-04',
 '2013-02-10',
 '2013-01-14',
 '2013-01-04',
 '2012-11-22',
 '2012-11-03',
 '2012-03-22',
 '2011-11-26',
 '2011-08-25',
 '2011-06-07',
 '2010-12-07',
 '2010-01-17',
 '2009-05-17',
 '2008-08-22',
 '2008-08-03',
 '2008-06-16',
 '2008-01-28',
 '2007-09-02',
 '2007-01-09',
 '2011-04-25',
 '2011-02-12',
 '2011-02-12',
 '2010-10-02',
 '2010-08-27',
 '2010-07-28',
 '2010-06-05',
 '2010-04-21',
 '2010-04-14',
 '2016-07-02',
 '2016-05-26',
 '2016-03-12',
 '2016-02-06',
 '2015-09-26',
 '2015-09-10',
 '2015-09-07',
 '2015-05-30',
 '2015-05-17',
 '2015-04-08',
 '2015-04-07',
 '2015-02-09',
 '2014-09-22',
 '2014-08-12',
 '2014-08-03',
 '2014-03-23',
 '2013-11-17',
 '2013-11-13',
 '2013-10-15',
 '2013-09-01',
 '2013-08-07',
 '2013-07-01',
 '2013-05-28',
 '2013-05-09',
 '2013-02-21',
 '2012-06-25',
 '2012-01-17',
 '2011-11-12',
 '2011-07-25',
 '2011-05-27',
 '2017-02-11',
 '2017-01-10',
 '2016-12-19',
 '2016-10-11',
 '2016-09-28',
 '2016-05-31',
 '2016-03-28',
 '2011-10-04',
 '2011-09-22',
 '2013-01-28',
 '2013-01-19',
 '2013-01-14',
 '2013-01-14',
 '2012-12-16',
 '2012-11-23',
 '2012-09-23',
 '2012-08-26',
 '2011-12-29',
 '2011-11-22',
 '2014-06-23',
 '2014-06-03',
 '2014-03-15',
 '2017-12-18',
 '2017-08-21',
 '2017-08-18',
 '2017-05-19',
 '2017-05-17',
 '2017-04-22',
 '2017-04-02',
 '2017-03-13',
 '2017-03-05',
 '2017-02-24',
 '2017-02-07',
 '2017-01-31',
 '2017-01-26',
 '2017-01-20',
 '2017-01-13',
 '2016-12-30',
 '2016-12-16',
 '2016-12-14',
 '2016-11-14',
 '2016-10-27',
 '2016-10-01',
 '2016-09-22',
 '2016-09-15',
 '2016-09-02',
 '2016-08-14',
 '2016-08-04',
 '2016-07-21',
 '2016-07-19',
 '2016-07-15',
 '2016-07-12',
 '2016-07-03',
 '2016-06-15',
 '2016-06-15',
 '2016-05-23',
 '2016-05-19',
 '2016-05-15',
 '2016-05-02',
 '2016-04-21',
 '2016-04-21',
 '2016-04-13',
 '2016-04-06',
 '2016-04-03',
 '2016-03-24',
 '2016-03-23',
 '2016-03-21',
 '2016-03-19',
 '2016-03-16',
 '2016-03-12',
 '2016-03-06',
 '2016-03-04',
 '2016-02-19',
 '2016-02-06',
 '2016-01-21',
 '2016-01-21',
 '2015-12-10',
 '2015-12-04',
 '2015-12-02',
 '2015-12-02',
 '2015-10-08',
 '2015-09-15',
 '2015-09-04',
 '2015-08-09',
 '2015-08-01',
 '2015-07-26',
 '2015-06-23',
 '2015-04-21',
 '2015-04-20',
 '2015-03-31',
 '2015-03-27',
 '2015-03-18',
 '2015-02-10',
 '2015-02-09',
 '2014-11-25',
 '2014-09-11',
 '2014-09-05',
 '2014-08-18',
 '2014-08-16',
 '2014-07-27',
 '2014-07-13',
 '2014-06-28',
 '2013-02-07',
 '2013-01-27',
 '2013-01-02',
 '2012-11-13',
 '2012-11-13',
 '2012-10-16',
 '2011-10-26',
 '2018-02-22',
 '2018-01-15',
 '2018-01-01',
 '2017-12-31',
 '2017-12-27',
 '2017-12-08',
 '2017-11-13',
 '2017-11-10',
 '2017-11-07',
 '2017-11-06',
 '2017-10-09',
 '2017-09-16',
 '2017-09-14',
 '2017-09-05',
 '2017-09-03',
 '2017-08-20',
 '2017-07-08',
 '2017-06-27',
 '2017-05-24',
 '2017-05-17',
 '2017-05-09',
 '2017-05-02',
 '2017-04-14',
 '2017-04-09',
 '2017-04-04',
 '2017-03-08',
 '2017-03-05',
 '2017-02-03',
 '2017-01-21',
 '2017-01-13',
 '2017-01-01',
 '2017-01-01',
 '2016-12-26',
 '2016-12-26',
 '2016-11-24',
 '2016-11-11',
 '2016-11-06',
 '2016-11-04',
 '2016-10-18',
 '2016-10-10',
 '2016-10-04',
 '2016-10-01',
 '2016-09-16',
 '2016-09-13',
 '2016-09-13',
 '2016-09-12',
 '2016-09-10',
 '2016-09-04',
 '2016-09-01',
 '2016-08-30',
 '2016-08-21',
 '2016-08-17',
 '2016-07-28',
 '2016-07-16',
 '2016-07-06',
 '2016-07-03',
 '2016-06-23',
 '2016-06-19',
 '2016-06-17',
 '2016-06-16',
 '2016-06-07',
 '2016-05-17',
 '2016-05-10',
 '2016-04-26',
 '2016-04-26',
 '2016-04-19',
 '2016-04-13',
 '2016-04-04',
 '2016-03-12',
 '2016-03-11',
 '2016-03-10',
 '2016-03-01',
 '2016-02-17',
 '2016-01-27',
 '2016-01-25',
 '2016-01-21',
 '2016-01-11',
 '2016-01-11',
 '2016-01-07',
 '2016-01-01',
 '2015-12-30',
 '2015-12-26',
 '2015-11-29',
 '2015-10-27',
 '2015-10-22',
 '2015-10-19',
 '2015-10-06',
 '2015-10-03',
 '2015-09-03',
 '2015-08-27',
 '2015-08-26',
 '2015-08-16',
 '2015-08-15',
 '2015-08-10',
 '2015-07-31',
 '2015-07-25',
 '2015-07-20',
 '2015-07-17',
 '2015-06-15',
 '2015-06-09',
 '2015-04-24',
 '2015-04-16',
 '2015-03-27',
 '2015-03-22',
 '2015-03-06',
 '2015-02-11',
 '2015-01-30',
 '2015-01-13',
 '2014-12-31',
 '2014-12-31',
 '2014-12-23',
 '2014-12-17',
 '2014-12-14',
 '2014-12-10',
 '2014-11-22',
 '2014-10-29',
 '2014-10-24',
 '2014-10-10',
 '2014-07-18',
 '2014-07-09',
 '2014-06-28',
 '2014-05-27',
 '2014-05-26',
 '2014-05-22',
 '2014-05-04',
 '2014-04-18',
 '2014-01-23',
 '2014-01-20',
 '2014-01-07',
 '2013-12-28',
 '2013-12-08',
 '2013-12-07',
 '2013-10-19',
 '2013-10-12',
 '2013-10-03',
 '2013-09-27',
 '2013-09-24',
 '2013-09-07',
 '2013-07-22',
 '2013-07-21',
 '2013-07-19',
 '2013-06-29',
 '2013-06-25',
 '2013-06-09',
 '2013-05-31',
 '2013-05-30',
 '2013-04-13',
 '2013-03-13',
 '2013-02-10',
 '2008-12-26',
 '2008-09-30',
 '2008-09-08',
 '2017-11-22',
 '2017-11-21',
 '2017-11-13',
 '2017-11-04',
 '2017-10-27',
 '2017-09-22',
 '2017-08-30',
 '2017-08-23',
 '2017-08-07',
 '2017-08-02',
 '2017-07-28',
 '2017-07-27',
 '2017-07-24',
 '2017-07-11',
 '2017-07-06',
 '2017-06-21',
 '2017-06-13',
 '2017-06-05',
 '2017-05-24',
 '2017-05-17',
 '2017-04-17',
 '2017-04-14',
 '2017-04-04',
 '2017-04-02',
 '2017-03-30',
 '2017-03-29',
 '2017-03-26',
 '2017-03-22',
 '2017-03-21',
 '2017-02-19',
 '2017-02-07',
 '2017-01-26',
 '2017-01-20',
 '2017-01-19',
 '2017-01-10',
 '2017-01-01',
 '2017-01-01',
 '2016-12-19',
 '2016-12-10',
 '2016-11-24',
 '2016-11-19',
 '2016-11-18',
 '2016-10-17',
 '2016-10-10',
 '2016-09-29',
 '2016-09-29',
 '2016-09-22',
 '2016-09-18',
 '2016-09-01',
 '2016-08-30',
 '2016-08-18',
 '2016-08-17',
 '2016-08-15',
 '2016-08-14',
 '2016-08-03',
 '2016-07-03',
 '2016-06-01',
 '2016-05-14',
 '2016-05-07',
 '2016-05-06',
 '2016-05-05',
 '2016-05-01',
 '2016-04-19',
 '2016-04-04',
 '2016-04-01',
 '2016-03-31',
 '2016-03-23',
 '2016-03-11',
 '2016-03-10',
 '2016-03-02',
 '2011-03-23',
 '2016-03-01',
 '2016-03-01',
 '2016-02-24',
 '2016-01-27',
 '2016-01-24',
 '2016-01-11',
 '2016-01-03',
 '2015-12-01',
 '2015-11-29',
 '2015-11-28',
 '2015-11-25',
 '2015-11-16',
 '2015-11-15',
 '2015-11-13',
 '2015-10-30',
 '2015-10-30',
 '2015-10-27',
 '2015-10-19',
 '2015-10-14',
 '2015-10-11',
 '2015-09-28',
 '2015-09-25',
 '2015-09-15',
 '2015-09-12',
 '2015-09-07',
 '2015-08-26',
 '2015-08-26',
 '2015-08-25',
 '2015-08-16',
 '2015-08-15',
 '2017-10-23',
 '2017-10-19',
 '2017-10-15',
 '2017-10-07',
 '2017-10-04',
 '2017-09-27',
 '2017-09-23',
 '2017-09-09',
 '2017-09-01',
 '2017-08-04',
 '2015-07-16',
 '2015-05-29',
 '2015-05-04',
 '2015-04-28',
 '2015-04-18',
 '2015-04-03',
 '2015-04-01',
 '2015-03-13',
 '2015-03-06',
 '2015-03-05',
 '2017-07-31',
 '2017-07-27',
 '2017-07-14',
 '2017-07-08',
 '2017-06-15',
 '2017-06-13',
 '2017-06-10',
 '2017-05-30',
 '2017-05-24',
 '2017-05-21',
 '2015-02-28',
 '2015-02-23',
 '2015-01-01',
 '2014-12-30',
 '2014-12-27',
 '2014-12-25',
 '2014-11-22',
 '2014-11-03',
 '2014-05-10',
 '2014-04-18',
 '2014-04-04',
 '2014-03-21',
 '2014-01-21',
 '2014-01-07',
 '2014-01-02',
 '2013-11-24',
 '2013-10-21',
 '2013-10-11',
 '2013-09-24',
 '2013-07-24',
 '2017-05-18',
 '2017-05-10',
 '2017-05-09',
 '2017-05-03',
 '2017-04-18',
 '2017-04-18',
 '2017-04-12',
 '2017-04-04',
 '2017-03-30',
 '2017-03-28',
 '2013-07-21',
 '2013-05-14',
 '2013-05-04',
 '2013-04-23',
 '2013-04-17',
 '2013-04-08',
 '2013-04-06',
 '2013-03-22',
 '2013-03-19',
 '2013-03-18',
 '2017-03-28',
 '2017-03-27',
 '2017-03-23',
 '2017-03-20',
 '2017-03-14',
 '2017-03-13',
 '2017-03-11',
 '2017-03-08',
 '2017-02-17',
 '2017-02-16',
 '2013-02-03',
 '2013-01-16',
 '2013-01-15',
 '2012-12-31',
 '2012-12-28',
 '2012-12-11',
 '2012-12-10',
 '2012-10-16',
 '2011-08-16',
 '2011-07-28',
 '2017-01-26',
 '2017-01-13',
 '2017-01-02',
 '2016-12-25',
 '2016-12-10',
 '2016-11-23',
 '2016-11-02',
 '2016-11-01',
 '2016-10-17',
 '2016-10-13',
 '2011-07-05',
 '2010-12-10',
 '2010-10-18',
 '2010-06-05',
 '2010-01-26',
 '2009-11-12',
 '2009-04-13',
 '2009-04-08',
 '2009-02-24',
 '2009-02-09',
 '2016-10-12',
 '2016-09-24',
 '2016-09-21',
 '2016-09-21',
 '2016-08-31',
 '2016-08-30',
 '2016-08-23',
 '2016-08-17',
 '2016-08-12',
 '2016-08-06',
 '2016-08-05',
 '2016-08-04',
 '2016-07-31',
 '2016-07-09',
 '2016-07-09',
 '2016-06-27',
 '2016-06-19',
 '2016-06-18',
 '2016-06-16',
 '2016-06-06',
 '2016-06-04',
 '2016-06-03',
 '2016-06-01',
 '2016-05-30',
 '2016-05-25',
 '2016-05-25',
 '2016-05-24',
 '2016-05-23',
 '2016-05-22',
 '2016-05-05',
 '2016-05-04',
 '2016-05-03',
 '2016-04-24',
 '2016-04-23',
 '2016-04-21',
 '2016-04-16',
 '2016-04-14',
 '2016-04-14',
 '2016-03-20',
 '2016-03-10',
 '2016-03-08',
 '2016-03-08',
 '2016-03-04',
 '2016-03-02',
 '2016-02-05',
 '2016-02-03',
 '2016-01-18',
 '2016-01-01',
 '2015-12-29',
 '2015-12-07',
 '2015-11-11',
 '2015-11-07',
 '2015-11-04',
 '2015-10-29',
 '2015-10-18',
 '2015-09-22',
 '2015-09-16',
 '2015-09-08',
 '2015-08-29',
 '2015-08-22',
 '2015-08-02',
 '2015-08-02',
 '2015-08-01',
 '2015-07-30',
 '2015-07-15',
 '2015-07-15',
 '2015-07-11',
 '2015-06-24',
 '2015-06-22',
 '2015-05-03',
 '2015-04-29',
 '2015-04-19',
 '2015-04-14',
 '2015-04-14',
 '2015-04-11',
 '2015-03-25',
 '2015-02-04',
 '2015-01-13',
 '2014-11-22',
 '2014-10-20',
 '2014-10-20',
 '2014-10-14',
 '2014-08-26',
 '2014-07-07',
 '2014-06-02',
 '2014-05-19',
 '2014-05-04',
 '2014-05-02',
 '2014-04-26',
 '2014-04-11',
 '2014-04-07',
 '2014-04-02',
 '2014-02-05',
 '2014-01-16',
 '2013-11-25',
 '2013-11-20',
 '2013-11-13',
 '2013-10-13',
 '2013-07-22',
 '2013-06-05',
 '2013-04-23',
 '2013-04-20',
 '2013-04-11',
 '2013-04-06',
 '2013-02-28',
 '2013-02-20',
 '2013-01-16',
 '2013-01-05',
 '2012-12-28',
 '2012-12-06',
 '2013-02-05',
 '2013-01-25',
 '2012-12-26',
 '2012-12-13',
 '2012-12-13',
 '2012-10-05',
 '2012-07-12',
 '2012-01-17',
 '2010-03-25',
 '2018-03-16',
 '2018-03-09',
 '2018-03-06',
 '2018-02-11',
 '2018-02-09',
 '2018-02-07',
 '2018-01-27',
 '2018-01-03',
 '2017-12-26',
 '2017-12-21',
 '2017-12-09',
 '2017-12-06',
 '2017-12-05',
 '2017-10-31',
 '2017-10-25',
 '2017-10-13',
 '2017-09-29',
 '2017-09-26',
 '2017-09-23',
 '2017-09-06',
 '2017-09-05',
 '2017-09-05',
 '2017-09-03',
 '2017-08-30',
 '2017-08-11',
 '2017-08-09',
 '2017-06-22',
 '2017-06-20',
 '2017-06-06',
 '2017-05-18',
 '2017-05-13',
 '2017-04-30',
 '2017-03-10',
 '2017-02-26',
 '2017-02-21',
 '2017-02-16',
 '2017-01-23',
 '2017-01-18',
 '2017-01-11',
 '2017-01-05',
 '2016-12-29',
 '2016-12-19',
 '2016-08-03',
 '2016-07-28',
 '2016-07-22',
 '2016-07-21',
 '2016-07-06',
 '2016-06-18',
 '2016-06-10',
 '2016-06-06',
 '2016-04-29',
 '2016-04-05',
 '2016-04-04',
 '2016-03-28',
 '2016-03-16',
 '2016-03-09',
 '2016-02-13',
 '2016-02-04',
 '2015-12-30',
 '2015-09-09',
 '2015-08-30',
 '2015-07-11',
 '2015-06-16',
 '2015-06-12',
 '2015-06-02',
 '2015-05-30',
 '2015-04-30',
 '2015-04-21',
 '2015-03-31',
 '2015-03-07',
 '2015-02-28',
 '2015-02-24',
 '2015-02-19',
 '2014-12-28',
 '2014-10-26',
 '2014-10-09',
 '2014-03-02',
 '2013-12-10',
 '2013-12-01',
 '2013-10-04',
 '2013-09-19',
 '2013-09-10',
 '2013-07-08',
 '2013-05-27',
 '2013-05-15',
 '2013-05-03',
 '2013-03-23',
 '2013-03-15',
 '2013-03-09',
 '2011-01-14',
 '2010-11-28',
 '2017-01-14',
 '2017-01-03',
 '2016-12-08',
 '2016-10-09',
 '2016-10-02',
 '2016-09-14',
 '2016-08-08',
 '2016-07-22',
 '2016-06-23',
 '2016-06-22',
 '2016-04-22',
 '2016-02-29',
 '2016-02-28',
 '2016-01-24',
 '2016-01-22',
 '2015-12-06',
 '2015-10-19',
 '2015-09-24',
 '2015-09-07',
 '2015-07-08',
 '2015-05-11',
 '2015-04-20',
 '2015-04-15',
 '2015-04-06',
 '2015-03-23',
 '2015-03-22',
 '2015-03-17',
 '2015-03-15',
 '2015-03-08',
 '2015-02-25',
 '2015-02-19',
 '2015-02-04',
 '2015-01-26',
 '2015-01-12',
 '2015-01-08',
 '2014-12-20',
 '2014-12-10',
 '2014-12-03',
 '2014-10-25',
 '2014-09-06',
 '2014-09-03',
 '2014-08-29',
 '2014-08-22',
 '2014-08-12',
 '2014-07-22',
 '2014-06-21',
 '2014-04-24',
 '2014-03-13',
 '2014-01-16',
 '2013-12-26',
 '2013-12-25',
 '2013-12-20',
 '2013-12-11',
 '2013-11-05',
 '2013-11-03',
 '2013-10-30',
 '2013-10-15',
 '2013-08-29',
 '2013-07-07',
 '2013-07-04',
 '2013-06-30',
 '2013-06-11',
 '2013-05-26',
 '2013-05-20',
 '2013-05-09',
 '2013-03-30',
 '2013-03-22',
 '2013-03-07',
 '2013-02-07',
 '2013-01-23',
 '2012-12-12',
 '2012-11-23',
 '2012-11-23',
 '2012-06-04',
 '2012-05-22',
 '2011-12-11',
 '2011-11-07',
 '2011-10-08',
 '2011-05-16',
 '2011-03-23',
 '2012-11-23',
 '2012-08-09',
 '2012-07-13',
 '2012-04-13',
 '2011-10-15',
 '2011-08-17',
 '2017-08-15',
 '2017-06-27',
 '2017-05-18',
 '2017-05-03',
 '2017-04-19',
 '2017-04-06',
 '2017-03-27',
 '2017-02-28',
 '2017-02-22',
 '2017-02-16',
 '2017-01-31',
 '2016-12-29',
 '2016-12-20',
 '2016-12-07',
 '2016-12-02',
 '2016-09-04',
 '2016-08-23',
 '2016-07-29',
 '2016-07-06',
 '2016-06-30',
 '2016-06-26',
 '2016-05-22',
 '2016-05-14',
 '2016-05-03',
 '2016-04-27',
 '2016-04-21',
 '2016-04-21',
 '2016-04-20',
 '2016-04-03',
 '2016-03-05',
 '2016-02-23',
 '2016-02-14',
 '2016-02-12',
 '2016-02-05',
 '2016-02-04',
 '2016-02-02',
 '2016-01-16',
 '2016-01-14',
 '2015-12-29',
 '2015-12-16',
 '2015-11-22',
 '2015-11-12',
 '2015-10-30',
 '2015-10-29',
 '2015-10-27',
 '2015-10-25',
 '2015-10-14',
 '2015-10-12',
 '2015-10-07',
 '2015-10-03',
 '2015-09-12',
 '2015-09-09',
 '2015-09-04',
 '2015-09-02',
 '2015-08-21',
 '2015-08-08',
 '2015-07-15',
 '2015-07-06',
 '2015-06-19',
 '2015-05-28',
 '2015-05-24',
 '2015-05-20',
 '2015-05-02',
 '2015-05-01',
 '2015-04-16',
 '2015-04-11',
 '2015-04-07',
 '2015-04-03',
 '2015-03-31',
 '2015-03-27',
 '2015-03-17',
 '2015-03-10',
 '2015-03-07',
 '2015-02-26',
 '2015-02-19',
 '2015-02-17',
 '2015-02-08',
 '2015-01-30',
 ...]

In [11]:
off_rating.date = date
off_rating.head()

         asin      reviewerID  rating        date
0  0140503528  A2WJLOXXIB7NF3     3.0  2006-11-03
1  0140503528  A1RKICUK0GG6VF     5.0  2006-05-09
2  0140503528  A1QA5E50M398VW     5.0  2006-03-11
3  0140503528  A3N0HBW8IP8CZQ     5.0  2001-01-24
4  0140503528  A1K1JW1C5CUSUZ     5.0  2000-07-30

In [12]:
off_rating.drop_duplicates(keep='first', inplace = True)
off_rating

               asin      reviewerID  rating        date
0        0140503528  A2WJLOXXIB7NF3     3.0  2006-11-03
1        0140503528  A1RKICUK0GG6VF     5.0  2006-05-09
2        0140503528  A1QA5E50M398VW     5.0  2006-03-11
3        0140503528  A3N0HBW8IP8CZQ     5.0  2001-01-24
4        0140503528  A1K1JW1C5CUSUZ     5.0  2000-07-30
...             ...             ...     ...         ...
5581308  B01HJF6JIA  A1MZM2RPZNEAV7     5.0  2018-02-20
5581309  B01HJF6JIA  A3MY8HH0ZQDXIL     5.0  2017-12-19
5581310  B01HJF6JIA  A1FNE2AS2H4UCN     5.0  2017-10-12
5581311  B01HJF6JIA  A13K8XJJE5OWBJ     5.0  2017-10-11
5581312  B01HJF6JIA  A3IN62EIHVZY9N     1.0  2017-04-22

[5396439 rows x 4 columns]

In [13]:
off_rating.isnull().sum()

asin          0
reviewerID    0
rating        0
date          0
dtype: int64

In [14]:
cds_rating.to_csv("CdsVinyl_rating.csv", index = False)
off_rating.to_csv("Office_rating.csv", index = False)