In [1]:
import pandas as pd

In [2]:
off_review = pd.read_csv("Office_reviews.csv")
off_review

,overall,verified,reviewTime,reviewerID,asin,reviewerName,reviewText,summary,class
0,4.0,True,2017-11-07,A2NIJTYWADLK57,0140503528,cotton clay,kids like story but while i really wanted a bo...,"good story, small size book though",good
1,4.0,True,2017-03-07,A2827D8EEURMP4,0140503528,emankcin,bought this used and it came in great conditio...,good,good
2,5.0,True,2016-06-25,APB6087F4J09J,0140503528,Starbucks Fan,every story and book about corduroy is fantast...,best books for all children,great
3,5.0,True,2016-02-21,A2DHERRZIPFU7X,0140503528,Caitlyn Jacobson,i purchased this book for my first grade class...,great for math!,great
4,5.0,False,2015-08-02,A2XCLJRGFANRC,0140503528,E. Ervin,having spent numerous years in an elementary s...,love corduroy,great
...,...,...,...,...,...,...,...,...,...
750260,5.0,True,2017-09-09,ACHG5QICJCS1F,B01HHLLLIO,Anky,delivered on time and is as expected.,5 stars,great
750261,5.0,True,2017-06-02,A1YB5J8SF6QX3L,B01HHLLLIO,DM,worked great.,good stuff,great
750262,5.0,True,2017-04-29,A3N4O7L4HBYJX4,B01HHLLLIO,Verdant Treasures,i used to score free ups 4x6 labels. the blac...,couldn't be happier with these labels,great
750263,5.0,True,2017-02-21,A2DR3CXSWWLYXY,B01HHLLLIO,C. F.,great,five stars,great
750264,4.0,True,2018-01-27,A3824BGRMFVT05,B01HINS07G,Tegan M. Reyes,struggled finding a sharpener and they didn't ...,four stars,good

In [3]:
off_review.isnull().sum()

overall          0
verified         0
reviewTime       0
reviewerID       0
asin             0
reviewerName    45
reviewText       0
summary         12
class            0
dtype: int64

In [4]:
off_review.reviewerName = off_review.reviewerName.fillna("Amazon Customer")
off_review.isnull().sum()

overall          0
verified         0
reviewTime       0
reviewerID       0
asin             0
reviewerName     0
reviewText       0
summary         12
class            0
dtype: int64

In [5]:
def cat_summary(row):  
    
    if row['overall'] == 1 :
        return 'One Star'
    elif row['overall'] == 2 :
        return 'Two Stars'
    elif row['overall'] == 3 :
        return 'Three Stars'
    elif row['overall'] == 4 :
        return 'Four Stars'
    elif row['overall'] == 5 :
        return 'Five Stars'

In [6]:
off_review.summary = off_review.summary.fillna(cat_summary)
off_review.isnull().sum()

overall         0
verified        0
reviewTime      0
reviewerID      0
asin            0
reviewerName    0
reviewText      0
summary         0
class           0
dtype: int64

In [7]:
off_meta = pd.read_csv("Office_meta.csv")
off_meta

,title,also_buy,brand,rank,also_view,main_cat,price,asin,primary_category,sub_cat,product_type
0,Sequential Spelling Level 1 Bundle with Studen...,[],stl distributors,439654.0,"['1935943065', '1935943073', 'B00IJH9Q4M', '00...",Office Products,32.90,0012624861,['Office Products'],['Office and School Supplies'],['Education and Crafts']
1,"Mathematics, Applications and Concepts, Course...",[],bailey,3839628.0,[],Books,8.62,0078652669,['Office Products'],['Office and School Supplies'],['Education and Crafts']
2,Pearson MyHistoryLab Online Access Code for Am...,[],pearson myhistorylab,1925354.0,[],Office Products,0.99,0136039847,['Office Products'],['Office and School Supplies'],['Paper']
3,A Pocket for Corduroy,"['0140501738', '0448421917', '0670063428', '04...",ingram book & distributor,422894.0,['0140501738'],Office Products,0.95,0140503528,['Office Products'],['Office and School Supplies'],['Education and Crafts']
4,Social Entrepreneurship: What Everyone Needs t...,"['0195334760', '1613630328', '1422104060', '15...",visit amazon's david bornstein page,110732.0,"['0195334760', '1586489569', '1613630328', '14...",Books,NaN,0195396332,['Office Products'],['Office and School Supplies'],['Education and Crafts']
...,...,...,...,...,...,...,...,...,...,...,...
306612,Nintendo Super Mario Bros. Lanyard with Mario ...,[],nintendo,439112.0,"['B01BF122TY', 'B06XGMZ2NT', 'B01MRXB87Q', 'B0...",Automotive,8.00,B01HJF4C66,['Office Products'],['Office and School Supplies'],"['Labels, Indexes and Stamps']"
306613,Lot of 2 - US American Flag &amp; Eagle US Pat...,"['B01K452Y5E', 'B00LMB1YQ0', 'B018EH7DZU', 'B0...",nykc,408194.0,"['B00LMB1YQ0', 'B01BCO7ID4', 'B01JO8H8NA', 'B0...",Office Products,4.99,B01HJF5WZQ,['Office Products'],['Office and School Supplies'],"['Forms, Recordkeeping and Money Handling']"
306614,CatchTheWave Natural Wood Pen Holder Folding S...,"['B00M0FACO2', 'B000J3X9VU']",catchthewave,307901.0,"['B07C6T4HQ1', 'B01J6DNIBO', 'B00QX6SEJO', 'B0...",Office Products,NaN,B01HJF6JIA,['Office Products'],['Office and School Supplies'],['Desk Accessories and Workspace Organizers']
306615,1pcs / Set Fashion Cartoon Blue Toy Story Phon...,[],lanyard,749930.0,[],Office Products,NaN,B01HJFOEQ4,['Office Products'],['Office and School Supplies'],['Paper']
306616,( PACK OF 5 ) FELLOWSHIP Full Transparent Desi...,[],srpc,1191960.0,[],Office Products,NaN,B01HJFPBLG,['Office Products'],['Office and School Supplies'],['Writing and Correction Supplies']

In [8]:
off_meta.isnull().sum()

title                    5
also_buy                 0
brand                   18
rank                  2623
also_view                0
main_cat                 0
price               140964
asin                     0
primary_category         0
sub_cat                  0
product_type             0
dtype: int64

In [9]:
off_meta['brand'] = off_meta['brand'].fillna(off_meta['brand'].mode()[0])
off_meta['title'] = off_meta['title'].fillna("unknown")
#off_meta['rank'] = off_meta['rank'].fillna(0)

off_meta.isnull().sum()

title                    0
also_buy                 0
brand                    0
rank                  2623
also_view                0
main_cat                 0
price               140964
asin                     0
primary_category         0
sub_cat                  0
product_type             0
dtype: int64

In [10]:
# off_merged = pd.merge(off_review , off_meta, how = 'left', on = 'asin')
# off_merged
off_merged = off_review.merge(off_meta, left_on = 'asin', right_on = 'asin')
off_merged

,overall,verified,reviewTime,reviewerID,asin,reviewerName,reviewText,summary,class,title,also_buy,brand,rank,also_view,main_cat,price,primary_category,sub_cat,product_type
0,4.0,True,2017-11-07,A2NIJTYWADLK57,0140503528,cotton clay,kids like story but while i really wanted a bo...,"good story, small size book though",good,A Pocket for Corduroy,"['0140501738', '0448421917', '0670063428', '04...",ingram book & distributor,422894.0,['0140501738'],Office Products,0.95,['Office Products'],['Office and School Supplies'],['Education and Crafts']
1,4.0,True,2017-03-07,A2827D8EEURMP4,0140503528,emankcin,bought this used and it came in great conditio...,good,good,A Pocket for Corduroy,"['0140501738', '0448421917', '0670063428', '04...",ingram book & distributor,422894.0,['0140501738'],Office Products,0.95,['Office Products'],['Office and School Supplies'],['Education and Crafts']
2,5.0,True,2016-06-25,APB6087F4J09J,0140503528,Starbucks Fan,every story and book about corduroy is fantast...,best books for all children,great,A Pocket for Corduroy,"['0140501738', '0448421917', '0670063428', '04...",ingram book & distributor,422894.0,['0140501738'],Office Products,0.95,['Office Products'],['Office and School Supplies'],['Education and Crafts']
3,5.0,True,2016-02-21,A2DHERRZIPFU7X,0140503528,Caitlyn Jacobson,i purchased this book for my first grade class...,great for math!,great,A Pocket for Corduroy,"['0140501738', '0448421917', '0670063428', '04...",ingram book & distributor,422894.0,['0140501738'],Office Products,0.95,['Office Products'],['Office and School Supplies'],['Education and Crafts']
4,5.0,False,2015-08-02,A2XCLJRGFANRC,0140503528,E. Ervin,having spent numerous years in an elementary s...,love corduroy,great,A Pocket for Corduroy,"['0140501738', '0448421917', '0670063428', '04...",ingram book & distributor,422894.0,['0140501738'],Office Products,0.95,['Office Products'],['Office and School Supplies'],['Education and Crafts']
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
749403,1.0,True,2017-06-01,A2LBDDKZ0ISPQU,B01HEFLV4M,Tanners Mom,barely held 1 piece of paper. amazon promptly...,me thinks not,poor,"LJY Magnetic Clip Fridge Paper Clips Holder, P...",[],ljy,309134.0,"['B01M03KZV2', 'B06XCN71JV', 'B01CT2SHIS', 'B0...",Office Products,NaN,['Office Products'],['Office and School Supplies'],['Desk Accessories and Workspace Organizers']
749404,5.0,True,2017-02-05,A30MBDOF8VZJWK,B01HEFLV4M,JenJen,<function categorise at 0x000002CD42BE5AF0>,clips,great,"LJY Magnetic Clip Fridge Paper Clips Holder, P...",[],ljy,309134.0,"['B01M03KZV2', 'B06XCN71JV', 'B01CT2SHIS', 'B0...",Office Products,NaN,['Office Products'],['Office and School Supplies'],['Desk Accessories and Workspace Organizers']
749405,5.0,True,2016-12-05,A2VVDFOWCEK3J2,B01HEFLV4M,mz,as advertised.,five stars,great,"LJY Magnetic Clip Fridge Paper Clips Holder, P...",[],ljy,309134.0,"['B01M03KZV2', 'B06XCN71JV', 'B01CT2SHIS', 'B0...",Office Products,NaN,['Office Products'],['Office and School Supplies'],['Desk Accessories and Workspace Organizers']
749406,5.0,True,2016-11-30,A2OSQT54KTT2GJ,B01HEFLV4M,Myrna W.,perfect for holding pads on the refrigerator. ...,five stars,great,"LJY Magnetic Clip Fridge Paper Clips Holder, P...",[],ljy,309134.0,"['B01M03KZV2', 'B06XCN71JV', 'B01CT2SHIS', 'B0...",Office Products,NaN,['Office Products'],['Office and School Supplies'],['Desk Accessories and Workspace Organizers']
749407,5.0,False,2016-10-28,A1LQOTRLG8TJKB,B01HEFLV4M,Rachel,does the job perfectly. nice strong magnets.,nice strong magnets,great,"LJY Magnetic Clip Fridge Paper Clips Holder, P...",[],ljy,309134.0,"['B01M03KZV2', 'B06XCN71JV', 'B01CT2SHIS', 'B0...",Office Products,NaN,['Office Products'],['Office and School Supplies'],['Desk Accessories and Workspace Organizers']

In [11]:
off_merged.shape

(749408, 19)

In [12]:
off_review.shape

(750265, 9)

In [13]:
off_merged.isnull().sum()

overall                  0
verified                 0
reviewTime               0
reviewerID               0
asin                     0
reviewerName             0
reviewText               0
summary                  0
class                    0
title                    0
also_buy                 0
brand                    0
rank                  5577
also_view                0
main_cat                 0
price               150716
primary_category         0
sub_cat                  0
product_type             0
dtype: int64

In [14]:
cds_review = pd.read_csv("CdsVinyl_reviews.csv") 
cds_review

,reviewerID,asin,reviewerName,verified,reviewText,overall,reviewTime,summary,class
0,A1H1DL4K669VQ9,0001393774,Judith Paladino,True,love it!! great seller!,5.0,2016-04-29,Five Stars,great
1,A3V5XBBT7OZG5G,0001393774,gflady,True,one of my very favourite albums from one of my...,5.0,2016-02-23,One of my very favourite albums from one of my...,great
2,A3SNL7UJY7GWBI,0001393774,Lady Leatherneck,True,"thank you jesus lord god, that brother green's...",5.0,2016-02-11,Five Stars,great
3,A3478QRKQDOPQ2,0001393774,jacki,True,i recall loving his other albums and maybe thi...,5.0,2015-11-28,forgot but I figured on some of these artists ...,great
4,A23M5VTSN2C3H1,0001393774,Caliope,True,keith green was a pioneer in the field of chri...,5.0,2014-12-16,and I have loved every album he did,great
...,...,...,...,...,...,...,...,...,...
1412821,A30ZM19J0CNAGJ,B01HJDG28E,Reggie: a music lover,True,night hawk is ten outstanding new recordings o...,5.0,2016-12-31,"My favorite cut is the cover of ""(Ghost) Rider...",great
1412822,APXJ8QC63EG38,B01HJG3VZI,Steven Schubak,True,ok,3.0,2018-07-25,Three Stars,average
1412823,A5HIGHKQPINEO,B01HJG3VZI,Oman,True,great music great sound love the music lots of...,5.0,2018-07-17,The sound quality and number of hits,great
1412824,A1B26TNQEWHQ4K,B01HJG3VZI,David W. Barsness,True,really good fun quality stuff,5.0,2018-06-23,5fer,great
1412825,A1KCWOF28NPM3M,B01HJG3VZI,Peter G.,True,"great 5 lp by the guess who, love all these al...",5.0,2017-11-04,Guess Who 5 Pack!,great

In [15]:
cds_review.isnull().sum()

reviewerID       0
asin             0
reviewerName    46
verified         0
reviewText       8
overall          0
reviewTime       0
summary         34
class            0
dtype: int64

In [16]:
cds_review.reviewerName = cds_review.reviewerName.fillna("Amazon Customer")
cds_review.summary = cds_review.summary.fillna(cat_summary)
cds_review.isnull().sum()

reviewerID      0
asin            0
reviewerName    0
verified        0
reviewText      8
overall         0
reviewTime      0
summary         0
class           0
dtype: int64

In [17]:
def categorise(row):  
    
    if row['overall'] == 1 :
        return 'poor'
    elif row['overall'] == 2 :
        return 'bad'
    elif row['overall'] == 3 :
        return 'average'
    elif row['overall'] == 4 :
        return 'good'
    elif row['overall'] == 5 :
        return 'great'

In [18]:
cds_review.reviewText = cds_review.reviewText.fillna(categorise)
cds_review.isnull().sum()

reviewerID      0
asin            0
reviewerName    0
verified        0
reviewText      0
overall         0
reviewTime      0
summary         0
class           0
dtype: int64

In [19]:
cds_meta = pd.read_csv("CdsVinyl_meta.csv") 
cds_meta

,title,also_buy,brand,rank,also_view,main_cat,price,asin,primary_category,sub_cat,product_type
0,Songs for the Shepherd,"['B0016CP2GS', 'B0000075PB', 'B0000275QQ', 'B0...",keith green,123896.0,"['B0016CP2GS', 'B00000I7JO', 'B00000I9AH', 'B0...",Digital Music,NaN,0001393774,['CDs & Vinyl'],['Christian'],['Christian']
1,Lift Him Up With Ron Kenoly VHS,"['6303908845', '6303646611', 'B000008GO1']",unknown artists,284935.0,['B00000DUDE'],Movies & TV,NaN,0001501348,['CDs & Vinyl'],['Christian'],['Pop & Contemporary']
2,I Love You,[],integrity music,1138833.0,[],Digital Music,NaN,0001515209,['CDs & Vinyl'],['Christian'],"[""Children's""]"
3,Hymns: 16 Classic Hymns for Children,"['B00000DPLJ', 'B000008UPG', 'B00BQH9RKA', 'B0...",sue gay,271064.0,"['B00000DPLL', '0843113006', 'B00BQH9RKA', 'B0...",Digital Music,NaN,0005072298,['CDs & Vinyl'],['Christian'],"[""Children's""]"
4,Christmas Carols,"['B0010WAC50', 'B00000DPLJ']",cedarmont kids,409293.0,"['B00000DPKG', 'B0010WAC50', 'B00000DPKH', 'B0...",Digital Music,NaN,0005121515,['CDs & Vinyl'],['Christian'],"[""Children's""]"
...,...,...,...,...,...,...,...,...,...,...,...
412320,Furnaces,"['B07CBLRXNP', 'B01MYB68L4', 'B07BZBD1TY', 'B0...",ed harcourt,251328.0,"['B07JBYSQ63', 'B00B8ZOZ84', 'B0048IDRJQ', 'B0...",Digital Music,9.79,B01HJ7FPAG,['CDs & Vinyl'],['Pop'],['Pop']
412321,Night Hawk,"['0718074963', 'B0012GMV5S', 'B00I89Y2SQ', 'B0...",charlie daniels band,68288.0,"['B07H5VY3LK', 'B00FLV06V6', 'B00I89Y2SQ', 'B0...",Digital Music,8.00,B01HJDG28E,['CDs & Vinyl'],['Country'],['Country']
412322,Original Album Classics,"['B00A7F17Z0', 'B00975L6O8', 'B00NMUCLBQ', 'B0...",dionne warwick,69386.0,"['B00A7F17Z0', 'B0000032WJ', 'B00000IFVX', 'B0...",Digital Music,14.56,B01HJG3UQI,['CDs & Vinyl'],['Pop'],['Vocal Pop']
412323,Original Album Classics,"['B06Y1L22WT', 'B017CJL0BO', 'B005JS7VTQ', 'B0...",the guess who,1795.0,"['B000CNE11O', 'B00000I0QI', 'B0042OZDP2', 'B0...",Digital Music,17.28,B01HJG3VZI,['CDs & Vinyl'],['Pop'],['Pop']
412324,Americana,[],diesel,1759107.0,[],Digital Music,20.04,B01HJHLNIY,['CDs & Vinyl'],['Pop'],['Pop']

In [20]:
cds_meta.isnull().sum()

title                   75
also_buy                 0
brand                   27
rank                  4533
also_view                0
main_cat                 0
price               114451
asin                     0
primary_category         0
sub_cat                  0
product_type             0
dtype: int64

In [21]:
cds_meta['brand'] = cds_meta['brand'].fillna(cds_meta['brand'].mode()[0])
cds_meta['title'] = cds_meta['title'].fillna("unknown")
#cds_meta['rank'] = cds_meta['rank'].fillna(0) 


cds_meta.isnull().sum()

title                    0
also_buy                 0
brand                    0
rank                  4533
also_view                0
main_cat                 0
price               114451
asin                     0
primary_category         0
sub_cat                  0
product_type             0
dtype: int64

In [22]:
cds_meta.shape

(412325, 11)

In [23]:
cds_review.shape

(1412826, 9)

In [24]:
cds_merged = cds_review.merge(cds_meta, how = 'left', on = 'asin')
cds_merged

,reviewerID,asin,reviewerName,verified,reviewText,overall,reviewTime,summary,class,title,also_buy,brand,rank,also_view,main_cat,price,primary_category,sub_cat,product_type
0,A1H1DL4K669VQ9,0001393774,Judith Paladino,True,love it!! great seller!,5.0,2016-04-29,Five Stars,great,Songs for the Shepherd,"['B0016CP2GS', 'B0000075PB', 'B0000275QQ', 'B0...",keith green,123896.0,"['B0016CP2GS', 'B00000I7JO', 'B00000I9AH', 'B0...",Digital Music,NaN,['CDs & Vinyl'],['Christian'],['Christian']
1,A3V5XBBT7OZG5G,0001393774,gflady,True,one of my very favourite albums from one of my...,5.0,2016-02-23,One of my very favourite albums from one of my...,great,Songs for the Shepherd,"['B0016CP2GS', 'B0000075PB', 'B0000275QQ', 'B0...",keith green,123896.0,"['B0016CP2GS', 'B00000I7JO', 'B00000I9AH', 'B0...",Digital Music,NaN,['CDs & Vinyl'],['Christian'],['Christian']
2,A3SNL7UJY7GWBI,0001393774,Lady Leatherneck,True,"thank you jesus lord god, that brother green's...",5.0,2016-02-11,Five Stars,great,Songs for the Shepherd,"['B0016CP2GS', 'B0000075PB', 'B0000275QQ', 'B0...",keith green,123896.0,"['B0016CP2GS', 'B00000I7JO', 'B00000I9AH', 'B0...",Digital Music,NaN,['CDs & Vinyl'],['Christian'],['Christian']
3,A3478QRKQDOPQ2,0001393774,jacki,True,i recall loving his other albums and maybe thi...,5.0,2015-11-28,forgot but I figured on some of these artists ...,great,Songs for the Shepherd,"['B0016CP2GS', 'B0000075PB', 'B0000275QQ', 'B0...",keith green,123896.0,"['B0016CP2GS', 'B00000I7JO', 'B00000I9AH', 'B0...",Digital Music,NaN,['CDs & Vinyl'],['Christian'],['Christian']
4,A23M5VTSN2C3H1,0001393774,Caliope,True,keith green was a pioneer in the field of chri...,5.0,2014-12-16,and I have loved every album he did,great,Songs for the Shepherd,"['B0016CP2GS', 'B0000075PB', 'B0000275QQ', 'B0...",keith green,123896.0,"['B0016CP2GS', 'B00000I7JO', 'B00000I9AH', 'B0...",Digital Music,NaN,['CDs & Vinyl'],['Christian'],['Christian']
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1412821,A30ZM19J0CNAGJ,B01HJDG28E,Reggie: a music lover,True,night hawk is ten outstanding new recordings o...,5.0,2016-12-31,"My favorite cut is the cover of ""(Ghost) Rider...",great,Night Hawk,"['0718074963', 'B0012GMV5S', 'B00I89Y2SQ', 'B0...",charlie daniels band,68288.0,"['B07H5VY3LK', 'B00FLV06V6', 'B00I89Y2SQ', 'B0...",Digital Music,8.00,['CDs & Vinyl'],['Country'],['Country']
1412822,APXJ8QC63EG38,B01HJG3VZI,Steven Schubak,True,ok,3.0,2018-07-25,Three Stars,average,Original Album Classics,"['B06Y1L22WT', 'B017CJL0BO', 'B005JS7VTQ', 'B0...",the guess who,1795.0,"['B000CNE11O', 'B00000I0QI', 'B0042OZDP2', 'B0...",Digital Music,17.28,['CDs & Vinyl'],['Pop'],['Pop']
1412823,A5HIGHKQPINEO,B01HJG3VZI,Oman,True,great music great sound love the music lots of...,5.0,2018-07-17,The sound quality and number of hits,great,Original Album Classics,"['B06Y1L22WT', 'B017CJL0BO', 'B005JS7VTQ', 'B0...",the guess who,1795.0,"['B000CNE11O', 'B00000I0QI', 'B0042OZDP2', 'B0...",Digital Music,17.28,['CDs & Vinyl'],['Pop'],['Pop']
1412824,A1B26TNQEWHQ4K,B01HJG3VZI,David W. Barsness,True,really good fun quality stuff,5.0,2018-06-23,5fer,great,Original Album Classics,"['B06Y1L22WT', 'B017CJL0BO', 'B005JS7VTQ', 'B0...",the guess who,1795.0,"['B000CNE11O', 'B00000I0QI', 'B0042OZDP2', 'B0...",Digital Music,17.28,['CDs & Vinyl'],['Pop'],['Pop']
1412825,A1KCWOF28NPM3M,B01HJG3VZI,Peter G.,True,"great 5 lp by the guess who, love all these al...",5.0,2017-11-04,Guess Who 5 Pack!,great,Original Album Classics,"['B06Y1L22WT', 'B017CJL0BO', 'B005JS7VTQ', 'B0...",the guess who,1795.0,"['B000CNE11O', 'B00000I0QI', 'B0042OZDP2', 'B0...",Digital Music,17.28,['CDs & Vinyl'],['Pop'],['Pop']

In [25]:
cds_merged.isnull().sum()

reviewerID               0
asin                     0
reviewerName             0
verified                 0
reviewText               0
overall                  0
reviewTime               0
summary                  0
class                    0
title               142676
also_buy            142676
brand               142676
rank                144033
also_view           142676
main_cat            142676
price               393662
primary_category    142676
sub_cat             142676
product_type        142676
dtype: int64

In [26]:
cds_merged[cds_merged.main_cat.isnull()]

,reviewerID,asin,reviewerName,verified,reviewText,overall,reviewTime,summary,class,title,also_buy,brand,rank,also_view,main_cat,price,primary_category,sub_cat,product_type
5593,A2X6GEC6LCDN4S,B0000000MD,J. McAndrew,False,"""love for life"" and ""within attraction"" are so...",4.0,2004-07-23,Good CD,good,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5594,A1K4GDFTG7VNC6,B0000000MD,Farhan Qureshi,False,i believe this album has all but the few exper...,5.0,2002-05-14,A great compilation of Yanni's music!,great,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5595,A2JJGIJI8X6KRS,B0000000MD,Psboston7,False,and i shall introduce you to the sound of yann...,5.0,2002-03-06,Speak to me of the visual concept of Beautiful...,great,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5604,A303U1MOXG5R1F,B0000000MD,Sylviastel,False,i know what i get with a yanni's music. this i...,5.0,2014-07-17,"Beautiful, Inspiring Music!",great,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5605,A2M083F1WUVSIC,B0000000MD,Dr Ragan Lorraine Lavorata,True,"ok, he was on my myspace but account is no lon...",4.0,2014-07-03,Four Stars,good,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1412710,A31LT8PPB184FQ,B01HD7P1CY,Mark E. Navarre,True,great 40 anniversary edition! i love what stev...,5.0,2017-03-28,Great 40 Anniversary Edition!,great,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1412711,A2V0GWVLFFEQS7,B01HD7P1CY,autumn,True,always the one,5.0,2017-03-27,Five Stars,great,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1412715,A1SD6EKW57CU4Y,B01HDE6DQA,The Blue Man,False,"for the last 10 years, assemblage 23 have focu...",5.0,2017-01-05,Innovative and brilliant,great,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1412716,A2RHQNTCOBL2ZV,B01HDE6DQA,FallenC,True,fantastic album by tom shear. the sound qualit...,5.0,2016-11-16,Fantastic Album by Tom Shear,great,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1412717,A2N37UM6E4W10F,B01HDE6DQA,Cjs,True,another classic ebm album from one of the mast...,5.0,2016-11-09,Good,great,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
cds_merged = cds_merged.dropna(subset = 'main_cat')
cds_merged.isnull().sum()

reviewerID               0
asin                     0
reviewerName             0
verified                 0
reviewText               0
overall                  0
reviewTime               0
summary                  0
class                    0
title                    0
also_buy                 0
brand                    0
rank                  1357
also_view                0
main_cat                 0
price               250986
primary_category         0
sub_cat                  0
product_type             0
dtype: int64

In [28]:
cds_merged.shape

(1270150, 19)

In [29]:
data = [off_merged, cds_merged]
review = pd.concat(data,ignore_index = True)
review

,overall,verified,reviewTime,reviewerID,asin,reviewerName,reviewText,summary,class,title,also_buy,brand,rank,also_view,main_cat,price,primary_category,sub_cat,product_type
0,4.0,True,2017-11-07,A2NIJTYWADLK57,0140503528,cotton clay,kids like story but while i really wanted a bo...,"good story, small size book though",good,A Pocket for Corduroy,"['0140501738', '0448421917', '0670063428', '04...",ingram book & distributor,422894.0,['0140501738'],Office Products,0.95,['Office Products'],['Office and School Supplies'],['Education and Crafts']
1,4.0,True,2017-03-07,A2827D8EEURMP4,0140503528,emankcin,bought this used and it came in great conditio...,good,good,A Pocket for Corduroy,"['0140501738', '0448421917', '0670063428', '04...",ingram book & distributor,422894.0,['0140501738'],Office Products,0.95,['Office Products'],['Office and School Supplies'],['Education and Crafts']
2,5.0,True,2016-06-25,APB6087F4J09J,0140503528,Starbucks Fan,every story and book about corduroy is fantast...,best books for all children,great,A Pocket for Corduroy,"['0140501738', '0448421917', '0670063428', '04...",ingram book & distributor,422894.0,['0140501738'],Office Products,0.95,['Office Products'],['Office and School Supplies'],['Education and Crafts']
3,5.0,True,2016-02-21,A2DHERRZIPFU7X,0140503528,Caitlyn Jacobson,i purchased this book for my first grade class...,great for math!,great,A Pocket for Corduroy,"['0140501738', '0448421917', '0670063428', '04...",ingram book & distributor,422894.0,['0140501738'],Office Products,0.95,['Office Products'],['Office and School Supplies'],['Education and Crafts']
4,5.0,False,2015-08-02,A2XCLJRGFANRC,0140503528,E. Ervin,having spent numerous years in an elementary s...,love corduroy,great,A Pocket for Corduroy,"['0140501738', '0448421917', '0670063428', '04...",ingram book & distributor,422894.0,['0140501738'],Office Products,0.95,['Office Products'],['Office and School Supplies'],['Education and Crafts']
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019553,5.0,True,2016-12-31,A30ZM19J0CNAGJ,B01HJDG28E,Reggie: a music lover,night hawk is ten outstanding new recordings o...,"My favorite cut is the cover of ""(Ghost) Rider...",great,Night Hawk,"['0718074963', 'B0012GMV5S', 'B00I89Y2SQ', 'B0...",charlie daniels band,68288.0,"['B07H5VY3LK', 'B00FLV06V6', 'B00I89Y2SQ', 'B0...",Digital Music,8.00,['CDs & Vinyl'],['Country'],['Country']
2019554,3.0,True,2018-07-25,APXJ8QC63EG38,B01HJG3VZI,Steven Schubak,ok,Three Stars,average,Original Album Classics,"['B06Y1L22WT', 'B017CJL0BO', 'B005JS7VTQ', 'B0...",the guess who,1795.0,"['B000CNE11O', 'B00000I0QI', 'B0042OZDP2', 'B0...",Digital Music,17.28,['CDs & Vinyl'],['Pop'],['Pop']
2019555,5.0,True,2018-07-17,A5HIGHKQPINEO,B01HJG3VZI,Oman,great music great sound love the music lots of...,The sound quality and number of hits,great,Original Album Classics,"['B06Y1L22WT', 'B017CJL0BO', 'B005JS7VTQ', 'B0...",the guess who,1795.0,"['B000CNE11O', 'B00000I0QI', 'B0042OZDP2', 'B0...",Digital Music,17.28,['CDs & Vinyl'],['Pop'],['Pop']
2019556,5.0,True,2018-06-23,A1B26TNQEWHQ4K,B01HJG3VZI,David W. Barsness,really good fun quality stuff,5fer,great,Original Album Classics,"['B06Y1L22WT', 'B017CJL0BO', 'B005JS7VTQ', 'B0...",the guess who,1795.0,"['B000CNE11O', 'B00000I0QI', 'B0042OZDP2', 'B0...",Digital Music,17.28,['CDs & Vinyl'],['Pop'],['Pop']
2019557,5.0,True,2017-11-04,A1KCWOF28NPM3M,B01HJG3VZI,Peter G.,"great 5 lp by the guess who, love all these al...",Guess Who 5 Pack!,great,Original Album Classics,"['B06Y1L22WT', 'B017CJL0BO', 'B005JS7VTQ', 'B0...",the guess who,1795.0,"['B000CNE11O', 'B00000I0QI', 'B0042OZDP2', 'B0...",Digital Music,17.28,['CDs & Vinyl'],['Pop'],['Pop']

In [30]:
review.isnull().sum()

overall                  0
verified                 0
reviewTime               0
reviewerID               0
asin                     0
reviewerName             0
reviewText               0
summary                  0
class                    0
title                    0
also_buy                 0
brand                    0
rank                  6934
also_view                0
main_cat                 0
price               401702
primary_category         0
sub_cat                  0
product_type             0
dtype: int64

In [31]:
data = review[['overall','price','rank']]

train = data[0:n]

rank = []
for i in review['rank']:
    i = str(i)
    i = i.split(" ")[0]
    i = i.replace("['>#",'')
    rank.append(i)
    
rank
review['rank'] = rank  

review['rank'] = review['rank'].replace('[]', np.nan)
review['rank'] = review['rank'].replace("nan", np.nan)

review['rank'] = pd.to_numeric(review['rank'], downcast="float")

In [32]:
import numpy as np
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
data = data
imp_mean = IterativeImputer(random_state=0)
imp_mean.fit(data)
IterativeImputer(random_state = 10)
a = imp_mean.transform(data)
a

array([[4.00000e+00, 9.50000e-01, 4.22894e+05],
       [4.00000e+00, 9.50000e-01, 4.22894e+05],
       [5.00000e+00, 9.50000e-01, 4.22894e+05],
       ...,
       [5.00000e+00, 1.72800e+01, 1.79500e+03],
       [5.00000e+00, 1.72800e+01, 1.79500e+03],
       [5.00000e+00, 1.72800e+01, 1.79500e+03]])

In [33]:
data

         overall  price      rank
0            4.0   0.95  422894.0
1            4.0   0.95  422894.0
2            5.0   0.95  422894.0
3            5.0   0.95  422894.0
4            5.0   0.95  422894.0
...          ...    ...       ...
2019553      5.0   8.00   68288.0
2019554      3.0  17.28    1795.0
2019555      5.0  17.28    1795.0
2019556      5.0  17.28    1795.0
2019557      5.0  17.28    1795.0

[2019558 rows x 3 columns]

In [34]:
data[data.price.isnull()]

         overall  price      rank
11           5.0    NaN  787995.0
12           5.0    NaN  787995.0
13           5.0    NaN  787995.0
14           5.0    NaN  787995.0
15           5.0    NaN  787995.0
...          ...    ...       ...
2019505      4.0    NaN   35587.0
2019506      5.0    NaN   35587.0
2019507      5.0    NaN   35587.0
2019508      5.0    NaN   35587.0
2019509      5.0    NaN   35587.0

[401702 rows x 3 columns]

In [35]:
a = pd.DataFrame(a)
a.rename(columns = {0:'overall', 1:"price", 2:"rank"}, inplace = True)
a

         overall  price      rank
0            4.0   0.95  422894.0
1            4.0   0.95  422894.0
2            5.0   0.95  422894.0
3            5.0   0.95  422894.0
4            5.0   0.95  422894.0
...          ...    ...       ...
2019553      5.0   8.00   68288.0
2019554      3.0  17.28    1795.0
2019555      5.0  17.28    1795.0
2019556      5.0  17.28    1795.0
2019557      5.0  17.28    1795.0

[2019558 rows x 3 columns]

In [36]:
review['price'] = a.price
review['rank'] = a.rank

In [37]:
review.isnull().sum()

overall             0
verified            0
reviewTime          0
reviewerID          0
asin                0
reviewerName        0
reviewText          0
summary             0
class               0
title               0
also_buy            0
brand               0
rank                0
also_view           0
main_cat            0
price               0
primary_category    0
sub_cat             0
product_type        0
dtype: int64

In [ ]:
review.to_csv("final_reviews.csv", index = False)

overall 
verified 
reviewtime
reviewer id
asin
class
also buy
brand
rank
also view
main
primary
sub