In [1]:
import pandas as pd
import warnings 
warnings.filterwarnings('ignore')

In [2]:
off_rating = pd.read_csv("Office_rating.csv") 
off_rating

               asin      reviewerID  rating        date
0        0140503528  A2WJLOXXIB7NF3     3.0  2006-11-03
1        0140503528  A1RKICUK0GG6VF     5.0  2006-05-09
2        0140503528  A1QA5E50M398VW     5.0  2006-03-11
3        0140503528  A3N0HBW8IP8CZQ     5.0  2001-01-24
4        0140503528  A1K1JW1C5CUSUZ     5.0  2000-07-30
...             ...             ...     ...         ...
5396434  B01HJF6JIA  A1MZM2RPZNEAV7     5.0  2018-02-20
5396435  B01HJF6JIA  A3MY8HH0ZQDXIL     5.0  2017-12-19
5396436  B01HJF6JIA  A1FNE2AS2H4UCN     5.0  2017-10-12
5396437  B01HJF6JIA  A13K8XJJE5OWBJ     5.0  2017-10-11
5396438  B01HJF6JIA  A3IN62EIHVZY9N     1.0  2017-04-22

[5396439 rows x 4 columns]

In [3]:
off_meta = pd.read_csv("Office_meta.csv") 
off_meta

,title,also_buy,brand,rank,also_view,main_cat,price,asin,primary_category,sub_cat,product_type
0,Sequential Spelling Level 1 Bundle with Studen...,[],stl distributors,439654.0,"['1935943065', '1935943073', 'B00IJH9Q4M', '00...",Office Products,32.90,0012624861,['Office Products'],['Office and School Supplies'],['Education and Crafts']
1,"Mathematics, Applications and Concepts, Course...",[],bailey,3839628.0,[],Books,8.62,0078652669,['Office Products'],['Office and School Supplies'],['Education and Crafts']
2,Pearson MyHistoryLab Online Access Code for Am...,[],pearson myhistorylab,1925354.0,[],Office Products,0.99,0136039847,['Office Products'],['Office and School Supplies'],['Paper']
3,A Pocket for Corduroy,"['0140501738', '0448421917', '0670063428', '04...",ingram book & distributor,422894.0,['0140501738'],Office Products,0.95,0140503528,['Office Products'],['Office and School Supplies'],['Education and Crafts']
4,Social Entrepreneurship: What Everyone Needs t...,"['0195334760', '1613630328', '1422104060', '15...",visit amazon's david bornstein page,110732.0,"['0195334760', '1586489569', '1613630328', '14...",Books,NaN,0195396332,['Office Products'],['Office and School Supplies'],['Education and Crafts']
...,...,...,...,...,...,...,...,...,...,...,...
306612,Nintendo Super Mario Bros. Lanyard with Mario ...,[],nintendo,439112.0,"['B01BF122TY', 'B06XGMZ2NT', 'B01MRXB87Q', 'B0...",Automotive,8.00,B01HJF4C66,['Office Products'],['Office and School Supplies'],"['Labels, Indexes and Stamps']"
306613,Lot of 2 - US American Flag &amp; Eagle US Pat...,"['B01K452Y5E', 'B00LMB1YQ0', 'B018EH7DZU', 'B0...",nykc,408194.0,"['B00LMB1YQ0', 'B01BCO7ID4', 'B01JO8H8NA', 'B0...",Office Products,4.99,B01HJF5WZQ,['Office Products'],['Office and School Supplies'],"['Forms, Recordkeeping and Money Handling']"
306614,CatchTheWave Natural Wood Pen Holder Folding S...,"['B00M0FACO2', 'B000J3X9VU']",catchthewave,307901.0,"['B07C6T4HQ1', 'B01J6DNIBO', 'B00QX6SEJO', 'B0...",Office Products,NaN,B01HJF6JIA,['Office Products'],['Office and School Supplies'],['Desk Accessories and Workspace Organizers']
306615,1pcs / Set Fashion Cartoon Blue Toy Story Phon...,[],lanyard,749930.0,[],Office Products,NaN,B01HJFOEQ4,['Office Products'],['Office and School Supplies'],['Paper']
306616,( PACK OF 5 ) FELLOWSHIP Full Transparent Desi...,[],srpc,1191960.0,[],Office Products,NaN,B01HJFPBLG,['Office Products'],['Office and School Supplies'],['Writing and Correction Supplies']

In [4]:
off_merged = off_rating.merge(off_meta, how = 'left', on = 'asin')
off_merged

,asin,reviewerID,rating,date,title,also_buy,brand,rank,also_view,main_cat,price,primary_category,sub_cat,product_type
0,0140503528,A2WJLOXXIB7NF3,3.0,2006-11-03,A Pocket for Corduroy,"['0140501738', '0448421917', '0670063428', '04...",ingram book & distributor,422894.0,['0140501738'],Office Products,0.95,['Office Products'],['Office and School Supplies'],['Education and Crafts']
1,0140503528,A1RKICUK0GG6VF,5.0,2006-05-09,A Pocket for Corduroy,"['0140501738', '0448421917', '0670063428', '04...",ingram book & distributor,422894.0,['0140501738'],Office Products,0.95,['Office Products'],['Office and School Supplies'],['Education and Crafts']
2,0140503528,A1QA5E50M398VW,5.0,2006-03-11,A Pocket for Corduroy,"['0140501738', '0448421917', '0670063428', '04...",ingram book & distributor,422894.0,['0140501738'],Office Products,0.95,['Office Products'],['Office and School Supplies'],['Education and Crafts']
3,0140503528,A3N0HBW8IP8CZQ,5.0,2001-01-24,A Pocket for Corduroy,"['0140501738', '0448421917', '0670063428', '04...",ingram book & distributor,422894.0,['0140501738'],Office Products,0.95,['Office Products'],['Office and School Supplies'],['Education and Crafts']
4,0140503528,A1K1JW1C5CUSUZ,5.0,2000-07-30,A Pocket for Corduroy,"['0140501738', '0448421917', '0670063428', '04...",ingram book & distributor,422894.0,['0140501738'],Office Products,0.95,['Office Products'],['Office and School Supplies'],['Education and Crafts']
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5396434,B01HJF6JIA,A1MZM2RPZNEAV7,5.0,2018-02-20,CatchTheWave Natural Wood Pen Holder Folding S...,"['B00M0FACO2', 'B000J3X9VU']",catchthewave,307901.0,"['B07C6T4HQ1', 'B01J6DNIBO', 'B00QX6SEJO', 'B0...",Office Products,NaN,['Office Products'],['Office and School Supplies'],['Desk Accessories and Workspace Organizers']
5396435,B01HJF6JIA,A3MY8HH0ZQDXIL,5.0,2017-12-19,CatchTheWave Natural Wood Pen Holder Folding S...,"['B00M0FACO2', 'B000J3X9VU']",catchthewave,307901.0,"['B07C6T4HQ1', 'B01J6DNIBO', 'B00QX6SEJO', 'B0...",Office Products,NaN,['Office Products'],['Office and School Supplies'],['Desk Accessories and Workspace Organizers']
5396436,B01HJF6JIA,A1FNE2AS2H4UCN,5.0,2017-10-12,CatchTheWave Natural Wood Pen Holder Folding S...,"['B00M0FACO2', 'B000J3X9VU']",catchthewave,307901.0,"['B07C6T4HQ1', 'B01J6DNIBO', 'B00QX6SEJO', 'B0...",Office Products,NaN,['Office Products'],['Office and School Supplies'],['Desk Accessories and Workspace Organizers']
5396437,B01HJF6JIA,A13K8XJJE5OWBJ,5.0,2017-10-11,CatchTheWave Natural Wood Pen Holder Folding S...,"['B00M0FACO2', 'B000J3X9VU']",catchthewave,307901.0,"['B07C6T4HQ1', 'B01J6DNIBO', 'B00QX6SEJO', 'B0...",Office Products,NaN,['Office Products'],['Office and School Supplies'],['Desk Accessories and Workspace Organizers']
5396438,B01HJF6JIA,A3IN62EIHVZY9N,1.0,2017-04-22,CatchTheWave Natural Wood Pen Holder Folding S...,"['B00M0FACO2', 'B000J3X9VU']",catchthewave,307901.0,"['B07C6T4HQ1', 'B01J6DNIBO', 'B00QX6SEJO', 'B0...",Office Products,NaN,['Office Products'],['Office and School Supplies'],['Desk Accessories and Workspace Organizers']

In [5]:
off_merged.isnull().sum()

asin                      0
reviewerID                0
rating                    0
date                      0
title                  5117
also_buy               4260
brand                  4355
rank                  42830
also_view              4260
main_cat               4260
price               1434317
primary_category       4260
sub_cat                4260
product_type           4260
dtype: int64

In [6]:
off_merged = off_merged.dropna(subset = 'main_cat')
off_merged.isnull().sum()

asin                      0
reviewerID                0
rating                    0
date                      0
title                   857
also_buy                  0
brand                    95
rank                  38570
also_view                 0
main_cat                  0
price               1430057
primary_category          0
sub_cat                   0
product_type              0
dtype: int64

In [7]:
off_merged['title'] = off_merged['title'].fillna("Unknown")
off_merged['brand'] = off_merged['brand'].fillna(off_merged['brand'].mode()[0])
off_merged.isnull().sum()

asin                      0
reviewerID                0
rating                    0
date                      0
title                     0
also_buy                  0
brand                     0
rank                  38570
also_view                 0
main_cat                  0
price               1430057
primary_category          0
sub_cat                   0
product_type              0
dtype: int64

In [8]:
cds_rating = pd.read_csv("CdsVinyl_rating.csv") 
cds_rating

               asin      reviewerID  rating        date
0        0001393774  A171I27YBM4FL6     5.0  2016-04-29
1        0001393774  A1H1DL4K669VQ9     5.0  2016-04-29
2        0001393774  A23WIHT5886G36     5.0  2016-04-19
3        0001393774  A3SZNOJP8OL26X     5.0  2016-03-30
4        0001393774  A3V5XBBT7OZG5G     5.0  2016-02-23
...             ...             ...     ...         ...
4470324  B01HJG3VZI  A1KCWOF28NPM3M     5.0  2017-11-04
4470325  B01HJG3UQI   ASOJC2B605GDG     5.0  2017-04-24
4470326  B01HJG3UQI  A13EWHP1W5X77J     4.0  2016-12-06
4470327  B01HJG3UQI  A1QN6Z2E6M0S2D     5.0  2016-10-13
4470328  B01HJHLNIY   AF65C8QK9NNXP     5.0  2016-07-20

[4470329 rows x 4 columns]

In [9]:
cds_rating.isnull().sum()

asin          0
reviewerID    0
rating        0
date          0
dtype: int64

In [10]:
cds_meta = pd.read_csv("CdsVinyl_meta.csv") 
cds_meta

,title,also_buy,brand,rank,also_view,main_cat,price,asin,primary_category,sub_cat,product_type
0,Songs for the Shepherd,"['B0016CP2GS', 'B0000075PB', 'B0000275QQ', 'B0...",keith green,123896.0,"['B0016CP2GS', 'B00000I7JO', 'B00000I9AH', 'B0...",Digital Music,NaN,0001393774,['CDs & Vinyl'],['Christian'],['Christian']
1,Lift Him Up With Ron Kenoly VHS,"['6303908845', '6303646611', 'B000008GO1']",unknown artists,284935.0,['B00000DUDE'],Movies & TV,NaN,0001501348,['CDs & Vinyl'],['Christian'],['Pop & Contemporary']
2,I Love You,[],integrity music,1138833.0,[],Digital Music,NaN,0001515209,['CDs & Vinyl'],['Christian'],"[""Children's""]"
3,Hymns: 16 Classic Hymns for Children,"['B00000DPLJ', 'B000008UPG', 'B00BQH9RKA', 'B0...",sue gay,271064.0,"['B00000DPLL', '0843113006', 'B00BQH9RKA', 'B0...",Digital Music,NaN,0005072298,['CDs & Vinyl'],['Christian'],"[""Children's""]"
4,Christmas Carols,"['B0010WAC50', 'B00000DPLJ']",cedarmont kids,409293.0,"['B00000DPKG', 'B0010WAC50', 'B00000DPKH', 'B0...",Digital Music,NaN,0005121515,['CDs & Vinyl'],['Christian'],"[""Children's""]"
...,...,...,...,...,...,...,...,...,...,...,...
412320,Furnaces,"['B07CBLRXNP', 'B01MYB68L4', 'B07BZBD1TY', 'B0...",ed harcourt,251328.0,"['B07JBYSQ63', 'B00B8ZOZ84', 'B0048IDRJQ', 'B0...",Digital Music,9.79,B01HJ7FPAG,['CDs & Vinyl'],['Pop'],['Pop']
412321,Night Hawk,"['0718074963', 'B0012GMV5S', 'B00I89Y2SQ', 'B0...",charlie daniels band,68288.0,"['B07H5VY3LK', 'B00FLV06V6', 'B00I89Y2SQ', 'B0...",Digital Music,8.00,B01HJDG28E,['CDs & Vinyl'],['Country'],['Country']
412322,Original Album Classics,"['B00A7F17Z0', 'B00975L6O8', 'B00NMUCLBQ', 'B0...",dionne warwick,69386.0,"['B00A7F17Z0', 'B0000032WJ', 'B00000IFVX', 'B0...",Digital Music,14.56,B01HJG3UQI,['CDs & Vinyl'],['Pop'],['Vocal Pop']
412323,Original Album Classics,"['B06Y1L22WT', 'B017CJL0BO', 'B005JS7VTQ', 'B0...",the guess who,1795.0,"['B000CNE11O', 'B00000I0QI', 'B0042OZDP2', 'B0...",Digital Music,17.28,B01HJG3VZI,['CDs & Vinyl'],['Pop'],['Pop']
412324,Americana,[],diesel,1759107.0,[],Digital Music,20.04,B01HJHLNIY,['CDs & Vinyl'],['Pop'],['Pop']

In [11]:
cds_merged = cds_rating.merge(cds_meta, how = 'left', on = 'asin')
cds_merged

,asin,reviewerID,rating,date,title,also_buy,brand,rank,also_view,main_cat,price,primary_category,sub_cat,product_type
0,0001393774,A171I27YBM4FL6,5.0,2016-04-29,Songs for the Shepherd,"['B0016CP2GS', 'B0000075PB', 'B0000275QQ', 'B0...",keith green,123896.0,"['B0016CP2GS', 'B00000I7JO', 'B00000I9AH', 'B0...",Digital Music,NaN,['CDs & Vinyl'],['Christian'],['Christian']
1,0001393774,A1H1DL4K669VQ9,5.0,2016-04-29,Songs for the Shepherd,"['B0016CP2GS', 'B0000075PB', 'B0000275QQ', 'B0...",keith green,123896.0,"['B0016CP2GS', 'B00000I7JO', 'B00000I9AH', 'B0...",Digital Music,NaN,['CDs & Vinyl'],['Christian'],['Christian']
2,0001393774,A23WIHT5886G36,5.0,2016-04-19,Songs for the Shepherd,"['B0016CP2GS', 'B0000075PB', 'B0000275QQ', 'B0...",keith green,123896.0,"['B0016CP2GS', 'B00000I7JO', 'B00000I9AH', 'B0...",Digital Music,NaN,['CDs & Vinyl'],['Christian'],['Christian']
3,0001393774,A3SZNOJP8OL26X,5.0,2016-03-30,Songs for the Shepherd,"['B0016CP2GS', 'B0000075PB', 'B0000275QQ', 'B0...",keith green,123896.0,"['B0016CP2GS', 'B00000I7JO', 'B00000I9AH', 'B0...",Digital Music,NaN,['CDs & Vinyl'],['Christian'],['Christian']
4,0001393774,A3V5XBBT7OZG5G,5.0,2016-02-23,Songs for the Shepherd,"['B0016CP2GS', 'B0000075PB', 'B0000275QQ', 'B0...",keith green,123896.0,"['B0016CP2GS', 'B00000I7JO', 'B00000I9AH', 'B0...",Digital Music,NaN,['CDs & Vinyl'],['Christian'],['Christian']
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4470324,B01HJG3VZI,A1KCWOF28NPM3M,5.0,2017-11-04,Original Album Classics,"['B06Y1L22WT', 'B017CJL0BO', 'B005JS7VTQ', 'B0...",the guess who,1795.0,"['B000CNE11O', 'B00000I0QI', 'B0042OZDP2', 'B0...",Digital Music,17.28,['CDs & Vinyl'],['Pop'],['Pop']
4470325,B01HJG3UQI,ASOJC2B605GDG,5.0,2017-04-24,Original Album Classics,"['B00A7F17Z0', 'B00975L6O8', 'B00NMUCLBQ', 'B0...",dionne warwick,69386.0,"['B00A7F17Z0', 'B0000032WJ', 'B00000IFVX', 'B0...",Digital Music,14.56,['CDs & Vinyl'],['Pop'],['Vocal Pop']
4470326,B01HJG3UQI,A13EWHP1W5X77J,4.0,2016-12-06,Original Album Classics,"['B00A7F17Z0', 'B00975L6O8', 'B00NMUCLBQ', 'B0...",dionne warwick,69386.0,"['B00A7F17Z0', 'B0000032WJ', 'B00000IFVX', 'B0...",Digital Music,14.56,['CDs & Vinyl'],['Pop'],['Vocal Pop']
4470327,B01HJG3UQI,A1QN6Z2E6M0S2D,5.0,2016-10-13,Original Album Classics,"['B00A7F17Z0', 'B00975L6O8', 'B00NMUCLBQ', 'B0...",dionne warwick,69386.0,"['B00A7F17Z0', 'B0000032WJ', 'B00000IFVX', 'B0...",Digital Music,14.56,['CDs & Vinyl'],['Pop'],['Vocal Pop']
4470328,B01HJHLNIY,AF65C8QK9NNXP,5.0,2016-07-20,Americana,[],diesel,1759107.0,[],Digital Music,20.04,['CDs & Vinyl'],['Pop'],['Pop']

In [12]:
cds_merged.isnull().sum()

asin                      0
reviewerID                0
rating                    0
date                      0
title                380673
also_buy             380503
brand                380648
rank                 390531
also_view            380503
main_cat             380503
price               1229815
primary_category     380503
sub_cat              380503
product_type         380503
dtype: int64

In [13]:
cds_merged = cds_merged.dropna(subset = "main_cat")
cds_merged

,asin,reviewerID,rating,date,title,also_buy,brand,rank,also_view,main_cat,price,primary_category,sub_cat,product_type
0,0001393774,A171I27YBM4FL6,5.0,2016-04-29,Songs for the Shepherd,"['B0016CP2GS', 'B0000075PB', 'B0000275QQ', 'B0...",keith green,123896.0,"['B0016CP2GS', 'B00000I7JO', 'B00000I9AH', 'B0...",Digital Music,NaN,['CDs & Vinyl'],['Christian'],['Christian']
1,0001393774,A1H1DL4K669VQ9,5.0,2016-04-29,Songs for the Shepherd,"['B0016CP2GS', 'B0000075PB', 'B0000275QQ', 'B0...",keith green,123896.0,"['B0016CP2GS', 'B00000I7JO', 'B00000I9AH', 'B0...",Digital Music,NaN,['CDs & Vinyl'],['Christian'],['Christian']
2,0001393774,A23WIHT5886G36,5.0,2016-04-19,Songs for the Shepherd,"['B0016CP2GS', 'B0000075PB', 'B0000275QQ', 'B0...",keith green,123896.0,"['B0016CP2GS', 'B00000I7JO', 'B00000I9AH', 'B0...",Digital Music,NaN,['CDs & Vinyl'],['Christian'],['Christian']
3,0001393774,A3SZNOJP8OL26X,5.0,2016-03-30,Songs for the Shepherd,"['B0016CP2GS', 'B0000075PB', 'B0000275QQ', 'B0...",keith green,123896.0,"['B0016CP2GS', 'B00000I7JO', 'B00000I9AH', 'B0...",Digital Music,NaN,['CDs & Vinyl'],['Christian'],['Christian']
4,0001393774,A3V5XBBT7OZG5G,5.0,2016-02-23,Songs for the Shepherd,"['B0016CP2GS', 'B0000075PB', 'B0000275QQ', 'B0...",keith green,123896.0,"['B0016CP2GS', 'B00000I7JO', 'B00000I9AH', 'B0...",Digital Music,NaN,['CDs & Vinyl'],['Christian'],['Christian']
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4470324,B01HJG3VZI,A1KCWOF28NPM3M,5.0,2017-11-04,Original Album Classics,"['B06Y1L22WT', 'B017CJL0BO', 'B005JS7VTQ', 'B0...",the guess who,1795.0,"['B000CNE11O', 'B00000I0QI', 'B0042OZDP2', 'B0...",Digital Music,17.28,['CDs & Vinyl'],['Pop'],['Pop']
4470325,B01HJG3UQI,ASOJC2B605GDG,5.0,2017-04-24,Original Album Classics,"['B00A7F17Z0', 'B00975L6O8', 'B00NMUCLBQ', 'B0...",dionne warwick,69386.0,"['B00A7F17Z0', 'B0000032WJ', 'B00000IFVX', 'B0...",Digital Music,14.56,['CDs & Vinyl'],['Pop'],['Vocal Pop']
4470326,B01HJG3UQI,A13EWHP1W5X77J,4.0,2016-12-06,Original Album Classics,"['B00A7F17Z0', 'B00975L6O8', 'B00NMUCLBQ', 'B0...",dionne warwick,69386.0,"['B00A7F17Z0', 'B0000032WJ', 'B00000IFVX', 'B0...",Digital Music,14.56,['CDs & Vinyl'],['Pop'],['Vocal Pop']
4470327,B01HJG3UQI,A1QN6Z2E6M0S2D,5.0,2016-10-13,Original Album Classics,"['B00A7F17Z0', 'B00975L6O8', 'B00NMUCLBQ', 'B0...",dionne warwick,69386.0,"['B00A7F17Z0', 'B0000032WJ', 'B00000IFVX', 'B0...",Digital Music,14.56,['CDs & Vinyl'],['Pop'],['Vocal Pop']
4470328,B01HJHLNIY,AF65C8QK9NNXP,5.0,2016-07-20,Americana,[],diesel,1759107.0,[],Digital Music,20.04,['CDs & Vinyl'],['Pop'],['Pop']

In [14]:
cds_merged.isnull().sum()

asin                     0
reviewerID               0
rating                   0
date                     0
title                  170
also_buy                 0
brand                  145
rank                 10028
also_view                0
main_cat                 0
price               849312
primary_category         0
sub_cat                  0
product_type             0
dtype: int64

In [15]:
cds_merged['title'] = cds_merged['title'].fillna("Unknown")
cds_merged['brand'] = cds_merged['brand'].fillna(cds_merged['brand'].mode()[0])
cds_merged.isnull().sum()

asin                     0
reviewerID               0
rating                   0
date                     0
title                    0
also_buy                 0
brand                    0
rank                 10028
also_view                0
main_cat                 0
price               849312
primary_category         0
sub_cat                  0
product_type             0
dtype: int64

In [16]:
data = [off_merged, cds_merged]
rating = pd.concat(data,ignore_index = True)
rating

,asin,reviewerID,rating,date,title,also_buy,brand,rank,also_view,main_cat,price,primary_category,sub_cat,product_type
0,0140503528,A2WJLOXXIB7NF3,3.0,2006-11-03,A Pocket for Corduroy,"['0140501738', '0448421917', '0670063428', '04...",ingram book & distributor,422894.0,['0140501738'],Office Products,0.95,['Office Products'],['Office and School Supplies'],['Education and Crafts']
1,0140503528,A1RKICUK0GG6VF,5.0,2006-05-09,A Pocket for Corduroy,"['0140501738', '0448421917', '0670063428', '04...",ingram book & distributor,422894.0,['0140501738'],Office Products,0.95,['Office Products'],['Office and School Supplies'],['Education and Crafts']
2,0140503528,A1QA5E50M398VW,5.0,2006-03-11,A Pocket for Corduroy,"['0140501738', '0448421917', '0670063428', '04...",ingram book & distributor,422894.0,['0140501738'],Office Products,0.95,['Office Products'],['Office and School Supplies'],['Education and Crafts']
3,0140503528,A3N0HBW8IP8CZQ,5.0,2001-01-24,A Pocket for Corduroy,"['0140501738', '0448421917', '0670063428', '04...",ingram book & distributor,422894.0,['0140501738'],Office Products,0.95,['Office Products'],['Office and School Supplies'],['Education and Crafts']
4,0140503528,A1K1JW1C5CUSUZ,5.0,2000-07-30,A Pocket for Corduroy,"['0140501738', '0448421917', '0670063428', '04...",ingram book & distributor,422894.0,['0140501738'],Office Products,0.95,['Office Products'],['Office and School Supplies'],['Education and Crafts']
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9482000,B01HJG3VZI,A1KCWOF28NPM3M,5.0,2017-11-04,Original Album Classics,"['B06Y1L22WT', 'B017CJL0BO', 'B005JS7VTQ', 'B0...",the guess who,1795.0,"['B000CNE11O', 'B00000I0QI', 'B0042OZDP2', 'B0...",Digital Music,17.28,['CDs & Vinyl'],['Pop'],['Pop']
9482001,B01HJG3UQI,ASOJC2B605GDG,5.0,2017-04-24,Original Album Classics,"['B00A7F17Z0', 'B00975L6O8', 'B00NMUCLBQ', 'B0...",dionne warwick,69386.0,"['B00A7F17Z0', 'B0000032WJ', 'B00000IFVX', 'B0...",Digital Music,14.56,['CDs & Vinyl'],['Pop'],['Vocal Pop']
9482002,B01HJG3UQI,A13EWHP1W5X77J,4.0,2016-12-06,Original Album Classics,"['B00A7F17Z0', 'B00975L6O8', 'B00NMUCLBQ', 'B0...",dionne warwick,69386.0,"['B00A7F17Z0', 'B0000032WJ', 'B00000IFVX', 'B0...",Digital Music,14.56,['CDs & Vinyl'],['Pop'],['Vocal Pop']
9482003,B01HJG3UQI,A1QN6Z2E6M0S2D,5.0,2016-10-13,Original Album Classics,"['B00A7F17Z0', 'B00975L6O8', 'B00NMUCLBQ', 'B0...",dionne warwick,69386.0,"['B00A7F17Z0', 'B0000032WJ', 'B00000IFVX', 'B0...",Digital Music,14.56,['CDs & Vinyl'],['Pop'],['Vocal Pop']
9482004,B01HJHLNIY,AF65C8QK9NNXP,5.0,2016-07-20,Americana,[],diesel,1759107.0,[],Digital Music,20.04,['CDs & Vinyl'],['Pop'],['Pop']

In [17]:
rating.isnull().sum()

asin                      0
reviewerID                0
rating                    0
date                      0
title                     0
also_buy                  0
brand                     0
rank                  48598
also_view                 0
main_cat                  0
price               2279369
primary_category          0
sub_cat                   0
product_type              0
dtype: int64

In [18]:
data = rating[['rating','price','rank']]

In [19]:
import numpy as np
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
data = data
imp_mean = IterativeImputer(random_state=0)
imp_mean.fit(data)
IterativeImputer(random_state = 10)
a = imp_mean.transform(data)
a

array([[3.000000e+00, 9.500000e-01, 4.228940e+05],
       [5.000000e+00, 9.500000e-01, 4.228940e+05],
       [5.000000e+00, 9.500000e-01, 4.228940e+05],
       ...,
       [4.000000e+00, 1.456000e+01, 6.938600e+04],
       [5.000000e+00, 1.456000e+01, 6.938600e+04],
       [5.000000e+00, 2.004000e+01, 1.759107e+06]])

In [20]:
a = pd.DataFrame(a)
a.rename(columns = {0:'overall', 1:"price", 2:"rank"}, inplace = True)
a

         overall  price       rank
0            3.0   0.95   422894.0
1            5.0   0.95   422894.0
2            5.0   0.95   422894.0
3            5.0   0.95   422894.0
4            5.0   0.95   422894.0
...          ...    ...        ...
9482000      5.0  17.28     1795.0
9482001      5.0  14.56    69386.0
9482002      4.0  14.56    69386.0
9482003      5.0  14.56    69386.0
9482004      5.0  20.04  1759107.0

[9482005 rows x 3 columns]

In [25]:
rating['price'] = a.price
rating['rank'] = a['rank']

In [26]:
rating.isnull().sum()

asin                0
reviewerID          0
rating              0
date                0
title               0
also_buy            0
brand               0
rank                0
also_view           0
main_cat            0
price               0
primary_category    0
sub_cat             0
product_type        0
dtype: int64

In [27]:
rating.head()

,asin,reviewerID,rating,date,title,also_buy,brand,rank,also_view,main_cat,price,primary_category,sub_cat,product_type
0,0140503528,A2WJLOXXIB7NF3,3.0,2006-11-03,A Pocket for Corduroy,"['0140501738', '0448421917', '0670063428', '04...",ingram book & distributor,422894.0,['0140501738'],Office Products,0.95,['Office Products'],['Office and School Supplies'],['Education and Crafts']
1,0140503528,A1RKICUK0GG6VF,5.0,2006-05-09,A Pocket for Corduroy,"['0140501738', '0448421917', '0670063428', '04...",ingram book & distributor,422894.0,['0140501738'],Office Products,0.95,['Office Products'],['Office and School Supplies'],['Education and Crafts']
2,0140503528,A1QA5E50M398VW,5.0,2006-03-11,A Pocket for Corduroy,"['0140501738', '0448421917', '0670063428', '04...",ingram book & distributor,422894.0,['0140501738'],Office Products,0.95,['Office Products'],['Office and School Supplies'],['Education and Crafts']
3,0140503528,A3N0HBW8IP8CZQ,5.0,2001-01-24,A Pocket for Corduroy,"['0140501738', '0448421917', '0670063428', '04...",ingram book & distributor,422894.0,['0140501738'],Office Products,0.95,['Office Products'],['Office and School Supplies'],['Education and Crafts']
4,0140503528,A1K1JW1C5CUSUZ,5.0,2000-07-30,A Pocket for Corduroy,"['0140501738', '0448421917', '0670063428', '04...",ingram book & distributor,422894.0,['0140501738'],Office Products,0.95,['Office Products'],['Office and School Supplies'],['Education and Crafts']

In [23]:
#rating2 = rating[7868129:]
#rating2

,asin,reviewerID,rating,date,title,also_buy,brand,rank,also_view,main_cat,price,primary_category,sub_cat,product_type
7868129,B00000143U,A1G3TIVS4RQSEH,5.0,2013-05-17,Complete Piano Music 3,"['B00000149K', 'B0000060CK', 'B000Q6ZUY4', 'B0...",franz liszt,<bound method NDFrame.rank of overall...,['B00000149K'],Digital Music,8.99,['CDs & Vinyl'],['Classical'],['Forms & Genres']
7868130,B00000143U,A1XKI53W1E891T,5.0,2007-07-29,Complete Piano Music 3,"['B00000149K', 'B0000060CK', 'B000Q6ZUY4', 'B0...",franz liszt,<bound method NDFrame.rank of overall...,['B00000149K'],Digital Music,8.99,['CDs & Vinyl'],['Classical'],['Forms & Genres']
7868131,B00000143U,A3GRVGD58ZUXD0,5.0,2006-06-28,Complete Piano Music 3,"['B00000149K', 'B0000060CK', 'B000Q6ZUY4', 'B0...",franz liszt,<bound method NDFrame.rank of overall...,['B00000149K'],Digital Music,8.99,['CDs & Vinyl'],['Classical'],['Forms & Genres']
7868132,B00000143U,A37FXUQ8Y9XAJK,4.0,2002-12-27,Complete Piano Music 3,"['B00000149K', 'B0000060CK', 'B000Q6ZUY4', 'B0...",franz liszt,<bound method NDFrame.rank of overall...,['B00000149K'],Digital Music,8.99,['CDs & Vinyl'],['Classical'],['Forms & Genres']
7868133,B00000143U,A3120BM9AE7W92,5.0,1999-11-10,Complete Piano Music 3,"['B00000149K', 'B0000060CK', 'B000Q6ZUY4', 'B0...",franz liszt,<bound method NDFrame.rank of overall...,['B00000149K'],Digital Music,8.99,['CDs & Vinyl'],['Classical'],['Forms & Genres']
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9482000,B01HJG3VZI,A1KCWOF28NPM3M,5.0,2017-11-04,Original Album Classics,"['B06Y1L22WT', 'B017CJL0BO', 'B005JS7VTQ', 'B0...",the guess who,<bound method NDFrame.rank of overall...,"['B000CNE11O', 'B00000I0QI', 'B0042OZDP2', 'B0...",Digital Music,17.28,['CDs & Vinyl'],['Pop'],['Pop']
9482001,B01HJG3UQI,ASOJC2B605GDG,5.0,2017-04-24,Original Album Classics,"['B00A7F17Z0', 'B00975L6O8', 'B00NMUCLBQ', 'B0...",dionne warwick,<bound method NDFrame.rank of overall...,"['B00A7F17Z0', 'B0000032WJ', 'B00000IFVX', 'B0...",Digital Music,14.56,['CDs & Vinyl'],['Pop'],['Vocal Pop']
9482002,B01HJG3UQI,A13EWHP1W5X77J,4.0,2016-12-06,Original Album Classics,"['B00A7F17Z0', 'B00975L6O8', 'B00NMUCLBQ', 'B0...",dionne warwick,<bound method NDFrame.rank of overall...,"['B00A7F17Z0', 'B0000032WJ', 'B00000IFVX', 'B0...",Digital Music,14.56,['CDs & Vinyl'],['Pop'],['Vocal Pop']
9482003,B01HJG3UQI,A1QN6Z2E6M0S2D,5.0,2016-10-13,Original Album Classics,"['B00A7F17Z0', 'B00975L6O8', 'B00NMUCLBQ', 'B0...",dionne warwick,<bound method NDFrame.rank of overall...,"['B00A7F17Z0', 'B0000032WJ', 'B00000IFVX', 'B0...",Digital Music,14.56,['CDs & Vinyl'],['Pop'],['Vocal Pop']
9482004,B01HJHLNIY,AF65C8QK9NNXP,5.0,2016-07-20,Americana,[],diesel,<bound method NDFrame.rank of overall...,[],Digital Music,20.04,['CDs & Vinyl'],['Pop'],['Pop']

In [24]:
#rating.to_csv("final_rating.csv", index = False)

KeyboardInterrupt:

In [ ]:
#rating2.to_csv("final_rating2.csv", index = False)